import { readFileSync } from "node:fs";
import { encode as msgpackEncode, decode as msgpackDecode } from "@msgpack/msgpack";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import {
  EncodedPayloadOptions,
  encryptedStrField,
  PayloadEncoder,
  WorkflowContext,
  WorkflowEncodingConfig,
  WorkflowPayloadCompressionError,
  WorkflowPayloadEncryptionError,
  WorkflowPayloadOffloadingError,
} from "../../src/extra/workflows/index.js";
import { importOptionalModule } from "../../src/extra/workflows/encoding/optional-module.js";
import { BlobNotFoundError } from "../../src/extra/workflows/encoding/storage/blob-storage.js";
import { InMemoryBlobStorage } from "./in-memory-blob-storage.js";

const storage = vi.hoisted(() => ({ current: undefined as unknown }));

vi.mock("../../src/extra/workflows/encoding/storage/s3.js", () => ({
  S3BlobStorage: { open: async () => storage.current },
}));

/**
 * Cases generated by the Python client with deterministic nonces and an
 * in-memory blob storage, see
 * client-python/src/mistralai/extra/tests/fixtures/workflow_offloading_parity.py.
 */
type FixtureConfig = {
  encryption?: { mode: "full" | "partial"; main_key: string; secondary_key?: string };
  offloading?: { min_size_bytes: number };
  compression?: { min_size_bytes: number; level: number };
};

type FixtureContext = { namespace: string; execution_id: string } | null;

type Fixtures = {
  keys: Record<string, string>;
  encode_network_input: Array<{
    name: string;
    config: FixtureConfig;
    context: FixtureContext;
    input: unknown;
    nonces: string[];
    expected: { b64payload: string; encoding_options: string[]; empty: boolean };
    blobs: Record<string, string>;
  }>;
  encode_payload_content: Array<{
    name: string;
    config: FixtureConfig;
    context: FixtureContext;
    options: { force_offload?: boolean; allow_offloading?: boolean };
    data_b64: string;
    nonces: string[];
    expected: { data_b64: string; encoding_options: string[] };
    blobs: Record<string, string>;
  }>;
  compressed: Array<{
    name: string;
    encoder_config: FixtureConfig;
    decoder_config: FixtureConfig;
    context: FixtureContext;
    input: unknown;
    encoded: { b64payload: string; encoding_options: string[]; empty: boolean };
    blobs: Record<string, string>;
  }>;
};

const fixtures: Fixtures = JSON.parse(
  readFileSync(
    new URL("./fixtures/workflow_offloading_parity.json", import.meta.url),
    "utf-8",
  ),
);

const S3_STORAGE = { storageProvider: "s3", bucketName: "parity-bucket" } as const;

function configFor(config: FixtureConfig): WorkflowEncodingConfig {
  const { encryption, offloading, compression } = config;
  return {
    ...(encryption
      ? {
        payloadEncryption: {
          mode: encryption.mode,
          mainKey: fixtures.keys[encryption.main_key]!,
          secondaryKey: encryption.secondary_key
            ? fixtures.keys[encryption.secondary_key]
            : undefined,
        },
      }
      : {}),
    ...(offloading
      ? {
        payloadOffloading: {
          minSizeBytes: offloading.min_size_bytes,
          storageConfig: S3_STORAGE,
        },
      }
      : {}),
    ...(compression
      ? {
        payloadCompression: {
          minSizeBytes: compression.min_size_bytes,
          algorithmConfig: { level: compression.level },
        },
      }
      : {}),
  };
}

function contextFor(context: FixtureContext): WorkflowContext | undefined {
  return context
    ? { namespace: context.namespace, executionId: context.execution_id }
    : undefined;
}

/** Makes the encoder draw its AES-GCM nonces from `nonces`, in order. */
function useNonces(nonces: string[]): () => void {
  const queue = [...nonces];
  vi.spyOn(globalThis.crypto, "getRandomValues").mockImplementation(
    <T extends ArrayBufferView | null>(array: T): T => {
      const nonce = queue.shift();
      if (nonce === undefined) throw new Error("Ran out of fixture nonces");
      (array as unknown as Uint8Array).set(Buffer.from(nonce, "hex"));
      return array;
    },
  );
  return () => expect(queue).toEqual([]);
}

/**
 * The compressed payload of an encoded input: its msgpack envelope, read from
 * the blob when it was offloaded. `undefined` when it wasn't compressed, or
 * was fully encrypted.
 */
function compressedEnvelope(
  encoded: { b64payload: string; encoding_options: string[] },
  blobs: Record<string, string>,
): { compression: unknown; payload: Uint8Array } | undefined {
  const options = encoded.encoding_options;
  if (
    !options.includes(EncodedPayloadOptions.Compressed)
    || options.includes(EncodedPayloadOptions.Encrypted)
  ) {
    return undefined;
  }
  let data = Buffer.from(encoded.b64payload, "base64");
  if (encoded.encoding_options.includes(EncodedPayloadOptions.Offloaded)) {
    data = Buffer.from(blobs[JSON.parse(data.toString()).key]!, "base64");
  }
  return msgpackDecode(data) as { compression: unknown; payload: Uint8Array };
}

/** Whether a zstd frame header records the content size, which Python requires. */
function hasContentSize(frame: Uint8Array): boolean {
  const descriptor = frame[4]!;
  const contentSizeFlag = descriptor >> 6;
  const singleSegment = (descriptor >> 5) & 1;
  return contentSizeFlag > 0 || singleSegment === 1;
}

/** The error `promise` rejects with. */
async function rejection(promise: Promise<unknown>): Promise<Error> {
  try {
    await promise;
  } catch (error) {
    return error as Error;
  }
  throw new Error("Expected the promise to reject");
}

const CONTEXT: WorkflowContext = { namespace: "ns", executionId: "exec" };
const KEY = "00".repeat(32);

let blobStorage: InMemoryBlobStorage;

beforeEach(() => {
  blobStorage = new InMemoryBlobStorage();
  storage.current = blobStorage;
});

afterEach(() => {
  vi.restoreAllMocks();
});

describe("workflow payload offloading parity with the Python client", () => {
  it.each(fixtures.encode_network_input.map((c) => [c.name, c] as const))(
    "encodeNetworkInput offloads the same bytes under the same key: %s",
    async (_name, testCase) => {
      const assertAllNoncesUsed = useNonces(testCase.nonces);

      const encoded = await new PayloadEncoder(configFor(testCase.config))
        .encodeNetworkInput(testCase.input, contextFor(testCase.context));

      expect(encoded).toEqual(testCase.expected);
      expect(blobStorage.base64Blobs()).toEqual(testCase.blobs);
      assertAllNoncesUsed();
    },
  );

  it.each(fixtures.encode_payload_content.map((c) => [c.name, c] as const))(
    "encodePayloadContent honors the offloading options: %s",
    async (_name, testCase) => {
      const assertAllNoncesUsed = useNonces(testCase.nonces);
      const errors = vi.spyOn(console, "error").mockImplementation(() => {});

      const { data, encodingOptions } = await new PayloadEncoder(
        configFor(testCase.config),
      ).encodePayloadContent(
        Buffer.from(testCase.data_b64, "base64"),
        contextFor(testCase.context),
        {
          forceOffload: testCase.options.force_offload,
          allowOffloading: testCase.options.allow_offloading,
        },
      );

      expect(Buffer.from(data).toString("base64")).toBe(testCase.expected.data_b64);
      expect(encodingOptions).toEqual(testCase.expected.encoding_options);
      expect(blobStorage.base64Blobs()).toEqual(testCase.blobs);
      // Like Python, offloading without a context is logged, not raised.
      expect(errors).toHaveBeenCalledTimes(testCase.context ? 0 : 1);
      assertAllNoncesUsed();
    },
  );

  it.each(fixtures.compressed.map((c) => [c.name, c] as const))(
    "decodeNetworkResult decodes Python's compressed payloads: %s",
    async (_name, testCase) => {
      blobStorage.reset(testCase.blobs);

      const decoded = await new PayloadEncoder(configFor(testCase.decoder_config))
        .decodeNetworkResult(testCase.encoded);

      expect(decoded).toEqual(testCase.input);
    },
  );

  it.each(fixtures.compressed.map((c) => [c.name, c] as const))(
    "encodeNetworkInput compresses like Python: %s",
    async (_name, testCase) => {
      const encoded = await new PayloadEncoder(configFor(testCase.encoder_config))
        .encodeNetworkInput(testCase.input, contextFor(testCase.context));
      const blobs = blobStorage.base64Blobs();

      expect(encoded.encoding_options).toEqual(testCase.encoded.encoding_options);
      expect(Object.keys(blobs)).toHaveLength(Object.keys(testCase.blobs).length);
      const ours = compressedEnvelope(encoded, blobs);
      const python = compressedEnvelope(testCase.encoded, testCase.blobs);
      expect(ours?.compression).toEqual(python?.compression);
      if (ours) expect(hasContentSize(ours.payload)).toBe(true);
      await expect(
        new PayloadEncoder(configFor(testCase.decoder_config))
          .decodeNetworkResult(encoded),
      ).resolves.toEqual(testCase.input);
    },
  );
});

describe("PayloadEncoder offloading", () => {
  const offloading = (minSizeBytes = 1): WorkflowEncodingConfig => ({
    payloadOffloading: { minSizeBytes, storageConfig: S3_STORAGE },
  });

  it("uploads a payload once, keyed by its content", async () => {
    const encoder = new PayloadEncoder(offloading());

    const first = await encoder.encodeNetworkInput({ a: 1 }, CONTEXT);
    const second = await encoder.encodeNetworkInput({ a: 1 }, CONTEXT);

    expect(second).toEqual(first);
    expect(blobStorage.uploads).toBe(1);
  });

  it("offloads at 1 MiB by default", async () => {
    const encoder = new PayloadEncoder({
      payloadOffloading: { storageConfig: S3_STORAGE },
    });

    const small = await encoder.encodeNetworkInput("x".repeat(1024 * 1024 - 3), CONTEXT);
    const large = await encoder.encodeNetworkInput("x".repeat(1024 * 1024 - 2), CONTEXT);

    expect(small.encoding_options).toEqual([]);
    expect(large.encoding_options).toEqual([EncodedPayloadOptions.Offloaded]);
  });

  it("keeps encrypted fields encrypted in the blob", async () => {
    const encoder = new PayloadEncoder({
      ...offloading(),
      payloadEncryption: { mode: "partial", mainKey: KEY },
    });
    const input = { data: "plain value", secret: encryptedStrField("secret value") };

    const encoded = await encoder.encodeNetworkInput(input, CONTEXT);
    const [blob] = blobStorage.blobs.values();

    expect(encoded.encoding_options).toEqual([
      EncodedPayloadOptions.PartiallyEncrypted,
      EncodedPayloadOptions.Offloaded,
    ]);
    expect(Buffer.from(blob!).toString()).toContain("plain value");
    expect(Buffer.from(blob!).toString()).not.toContain("secret value");
    await expect(encoder.decodeNetworkResult(encoded)).resolves.toEqual(input);
  });

  it("never offloads event payloads", async () => {
    const encoder = new PayloadEncoder(offloading());

    const { encodingOptions } = await encoder.encodeEventPayloadContent("{\"a\": 1}");

    expect(encodingOptions).toEqual([]);
    expect(blobStorage.uploads).toBe(0);
  });

  it("refuses offloaded payloads when offloading is not configured", async () => {
    const encoded = await new PayloadEncoder(offloading())
      .encodeNetworkInput({ a: 1 }, CONTEXT);
    const decoder = new PayloadEncoder({
      payloadEncryption: { mode: "full", mainKey: KEY },
    });

    await expect(decoder.decodeNetworkResult(encoded)).rejects.toThrow(
      /Payload offloading is not enabled/,
    );
  });

  it.each([
    ["not JSON", "not json"],
    ["no key", "{\"other\": \"x\"}"],
    ["a non-string key", "{\"key\": 1}"],
  ])("rejects an offloaded payload with %s", async (_name, data) => {
    const encoder = new PayloadEncoder(offloading());

    await expect(
      encoder.decodePayloadContent(new TextEncoder().encode(data), [
        EncodedPayloadOptions.Offloaded,
      ]),
    ).rejects.toThrow(/Invalid offloaded payload data/);
  });

  it("reports a missing blob", async () => {
    const encoder = new PayloadEncoder(offloading());
    const encoded = await encoder.encodeNetworkInput({ a: 1 }, CONTEXT);
    blobStorage.reset();

    const error = await rejection(encoder.decodeNetworkResult(encoded));

    expect(error).toBeInstanceOf(WorkflowPayloadOffloadingError);
    expect(error.cause).toBeInstanceOf(BlobNotFoundError);
  });

  it("wraps storage failures", async () => {
    const failure = new Error("network down");
    vi.spyOn(blobStorage, "uploadBlob").mockRejectedValue(failure);

    const error = await rejection(new PayloadEncoder(offloading())
      .encodeNetworkInput({ a: 1 }, CONTEXT));

    expect(error).toBeInstanceOf(WorkflowPayloadOffloadingError);
    expect(error.cause).toBe(failure);
  });

  it.each([
    ["S3 without bucketName", { storageProvider: "s3" }, /bucketName is required/],
    ["GCS without bucketId", { storageProvider: "gcs" }, /bucketId is required/],
    [
      "Azure without containerName",
      { storageProvider: "azure", azureConnectionString: "c" },
      /containerName is required/,
    ],
    [
      "Azure without credentials",
      { storageProvider: "azure", containerName: "c" },
      /Either azureConnectionString or azureStorageAccountUrl/,
    ],
    [
      "Azure with both credentials",
      {
        storageProvider: "azure",
        containerName: "c",
        azureConnectionString: "c",
        azureStorageAccountUrl: "https://a",
      },
      /mutually exclusive/,
    ],
    [
      "S3 with half the credentials",
      { bucketName: "b", awsAccessKeyId: "id" },
      /must be set together/,
    ],
    ["an unknown provider", { storageProvider: "ftp" }, /storageProvider/],
    ["Python-style keys", { bucket_name: "b" }, /bucket_name/],
  ])("rejects a storage config: %s", (_name, storageConfig, message) => {
    const create = () =>
      new PayloadEncoder({
        payloadOffloading: { storageConfig: storageConfig as never },
      });

    expect(create).toThrow(WorkflowPayloadOffloadingError);
    expect(create).toThrow(message);
  });

  it("rejects a config that enables nothing", () => {
    expect(() => new PayloadEncoder({})).toThrow(WorkflowPayloadEncryptionError);
    expect(() => new PayloadEncoder({})).toThrow(/At least one of/);
  });

  it("refuses encrypted payloads when encryption is not configured", async () => {
    await expect(
      new PayloadEncoder(offloading()).decodePayloadContent(
        new Uint8Array(32),
        [EncodedPayloadOptions.Encrypted],
      ),
    ).rejects.toThrow(/You must configure payload encryption/);
  });

  it("escapes the key prefix like Python's urllib.parse.quote", () => {
    expect(
      PayloadEncoder.blobStorageKeyPrefix({
        namespace: "a b/!'()*~-_.é",
        executionId: "x?#&",
      }),
    ).toBe("temporal-payload/a%20b%2F%21%27%28%29%2A~-_.%C3%A9/x%3F%23%26");
  });
});

describe("PayloadEncoder compression", () => {
  const compression = (level = 3): WorkflowEncodingConfig => ({
    payloadCompression: { minSizeBytes: 1, algorithmConfig: { level } },
  });
  const decoder = () =>
    new PayloadEncoder({ payloadEncryption: { mode: "full", mainKey: KEY } });

  function compressedInput(data: unknown) {
    return {
      b64payload: Buffer.from(msgpackEncode(data)).toString("base64"),
      encoding_options: [EncodedPayloadOptions.Compressed],
    };
  }

  it("decodes whatever level the frame was compressed with", async () => {
    const encoded = await new PayloadEncoder(compression(22))
      .encodeNetworkInput({ data: "x".repeat(2000) });
    const envelope = msgpackDecode(Buffer.from(encoded.b64payload, "base64")) as {
      payload: Uint8Array;
    };
    const tampered = compressedInput({
      compression: { algorithm: "zstd", level: 1 },
      payload: envelope.payload,
    });

    await expect(decoder().decodeNetworkResult(tampered)).resolves.toEqual({
      data: "x".repeat(2000),
    });
  });

  it("defaults the level of the stored config, like pydantic", async () => {
    const encoded = await new PayloadEncoder(compression())
      .encodeNetworkInput({ data: "x".repeat(2000) });
    const envelope = msgpackDecode(Buffer.from(encoded.b64payload, "base64")) as {
      payload: Uint8Array;
    };

    await expect(
      decoder().decodeNetworkResult(
        compressedInput({ compression: { algorithm: "zstd" }, payload: envelope.payload }),
      ),
    ).resolves.toEqual({ data: "x".repeat(2000) });
  });

  it.each([
    ["not msgpack", Buffer.from("compressed-data"), /Invalid compressed payload data/],
    [
      "an unknown algorithm",
      msgpackEncode({ compression: { algorithm: "lz4", level: 1 }, payload: new Uint8Array(1) }),
      /Invalid compressed payload metadata/,
    ],
    [
      "no algorithm",
      msgpackEncode({ compression: { level: 3 }, payload: new Uint8Array(1) }),
      /Invalid compressed payload metadata/,
    ],
    [
      "a non-binary payload",
      msgpackEncode({ compression: { algorithm: "zstd", level: 3 }, payload: 123 }),
      /Invalid compressed payload metadata/,
    ],
    [
      "corrupted zstd data",
      msgpackEncode({
        compression: { algorithm: "zstd", level: 3 },
        payload: new TextEncoder().encode("corrupted-data"),
      }),
      /Failed to decompress payload/,
    ],
  ])("rejects a compressed payload with %s", async (_name, data, message) => {
    const encoded = {
      b64payload: Buffer.from(data).toString("base64"),
      encoding_options: [EncodedPayloadOptions.Compressed],
    };

    const error = await rejection(decoder().decodeNetworkResult(encoded));

    expect(error).toBeInstanceOf(WorkflowPayloadCompressionError);
    expect(error.message).toMatch(message);
  });

  it.each([0, 23, 2.5])("rejects the compression level %j", (level) => {
    expect(() => new PayloadEncoder(compression(level))).toThrow(
      WorkflowPayloadCompressionError,
    );
  });

  it("compresses event payloads", async () => {
    const encoder = new PayloadEncoder({
      ...compression(),
      payloadOffloading: { minSizeBytes: 1, storageConfig: S3_STORAGE },
    });
    const payload = JSON.stringify({ data: "x".repeat(2000) });

    const { data, encodingOptions } = await encoder.encodeEventPayloadContent(payload);

    expect(encodingOptions).toEqual([EncodedPayloadOptions.Compressed]);
    expect(blobStorage.uploads).toBe(0);
    await expect(
      decoder().decodePayloadContent(data, encodingOptions),
    ).resolves.toEqual(new TextEncoder().encode(payload));
  });
});

describe("optional dependencies", () => {
  it("explains how to install a missing module", async () => {
    const error = await rejection(importOptionalModule(
      "@mistralai/not-installed",
      (cause) => new WorkflowPayloadOffloadingError("install it", { cause }),
    ));

    expect(error).toBeInstanceOf(WorkflowPayloadOffloadingError);
    expect(error.message).toBe("install it");
    expect(error.cause).toBeDefined();
  });
});
