import { readFileSync } from "node:fs";
import { inspect } from "node:util";
import { afterEach, describe, expect, it, vi } from "vitest";

import {
  EncodedPayloadOptions,
  encryptedStrField,
  generateTwoPartId,
  PayloadEncoder,
  PayloadEncryptionMode,
  WorkflowPayloadCompressionError,
  WorkflowPayloadEncryptionError,
  WorkflowPayloadOffloadingError,
} from "../../src/extra/workflows/index.js";

/**
 * Cases generated by the Python client with deterministic nonces, see
 * client-python/src/mistralai/extra/tests/fixtures/workflow_encryption_parity.py.
 */
type FixtureConfig = {
  mode: PayloadEncryptionMode;
  main_key: string;
  secondary_key?: string;
};

type Fixtures = {
  keys: Record<string, string>;
  encode_network_input: Array<{
    name: string;
    config: FixtureConfig;
    input: unknown;
    nonces: string[];
    expected: unknown;
  }>;
  encode_payload_content: Array<{
    name: string;
    config: FixtureConfig;
    data_b64: string;
    nonces: string[];
    expected: { data_b64: string; encoding_options: string[] };
  }>;
  decode_network_result: Array<{
    name: string;
    config: FixtureConfig;
    encoded: unknown;
    expected: unknown;
  }>;
  decode_event_payload: Array<{
    name: string;
    config: FixtureConfig;
    payload: Record<string, unknown>;
    expected: unknown;
  }>;
};

const fixtures: Fixtures = JSON.parse(
  readFileSync(
    new URL("./fixtures/workflow_encryption_parity.json", import.meta.url),
    "utf-8",
  ),
);

function encoderFor(config: FixtureConfig): PayloadEncoder {
  return new PayloadEncoder({
    payloadEncryption: {
      mode: config.mode,
      mainKey: fixtures.keys[config.main_key]!,
      secondaryKey: config.secondary_key
        ? fixtures.keys[config.secondary_key]
        : undefined,
    },
  });
}

/** Makes the encoder draw its AES-GCM nonces from `nonces`, in order. */
function useNonces(nonces: string[]): () => void {
  const queue = [...nonces];
  vi.spyOn(globalThis.crypto, "getRandomValues").mockImplementation(
    <T extends ArrayBufferView | null>(array: T): T => {
      const nonce = queue.shift();
      if (nonce === undefined) throw new Error("Ran out of fixture nonces");
      (array as unknown as Uint8Array).set(Buffer.from(nonce, "hex"));
      return array;
    },
  );
  return () => expect(queue).toEqual([]);
}

afterEach(() => {
  vi.restoreAllMocks();
});

describe("workflow payload encryption parity with the Python client", () => {
  it.each(fixtures.encode_network_input.map((c) => [c.name, c] as const))(
    "encodeNetworkInput produces the same bytes: %s",
    async (_name, testCase) => {
      const assertAllNoncesUsed = useNonces(testCase.nonces);

      const encoded = await encoderFor(testCase.config).encodeNetworkInput(
        testCase.input,
      );

      expect(encoded).toEqual(testCase.expected);
      assertAllNoncesUsed();
    },
  );

  it.each(fixtures.encode_payload_content.map((c) => [c.name, c] as const))(
    "encodePayloadContent produces the same bytes: %s",
    async (_name, testCase) => {
      const assertAllNoncesUsed = useNonces(testCase.nonces);

      const { data, encodingOptions } = await encoderFor(testCase.config)
        .encodePayloadContent(Buffer.from(testCase.data_b64, "base64"));

      expect(Buffer.from(data).toString("base64")).toEqual(
        testCase.expected.data_b64,
      );
      expect(encodingOptions).toEqual(testCase.expected.encoding_options);
      assertAllNoncesUsed();
    },
  );

  it.each(fixtures.decode_network_result.map((c) => [c.name, c] as const))(
    "decodeNetworkResult decodes Python payloads after key rotation: %s",
    async (_name, testCase) => {
      const decoded = await encoderFor(testCase.config).decodeNetworkResult(
        testCase.encoded,
      );

      expect(decoded).toEqual(testCase.expected);
    },
  );

  it.each(fixtures.decode_event_payload.map((c) => [c.name, c] as const))(
    "decodeEventPayload decodes Python event payloads: %s",
    async (_name, testCase) => {
      const decoded = await encoderFor(testCase.config).decodeEventPayload(
        testCase.payload,
      );

      expect(decoded).toEqual(testCase.expected);
    },
  );

  it("generates the same two-part execution IDs", async () => {
    // uuid5-based, from Python's generate_two_part_id("my-workflow", "seed-2")
    await expect(generateTwoPartId("my-workflow", "seed-2")).resolves.toBe(
      "f332d40360e855878af643b709a85bff87e5f21ec8155e9b8f69898f8dd094f5",
    );
  });
});

describe("PayloadEncoder", () => {
  const key = fixtures.keys["main"]!;
  const otherKey = fixtures.keys["secondary"]!;

  it.each([PayloadEncryptionMode.Full, PayloadEncryptionMode.Partial])(
    "round-trips inputs with random nonces in %s mode",
    async (mode) => {
      const encoder = new PayloadEncoder({
        payloadEncryption: { mode, mainKey: key },
      });
      const input = {
        user: "alice",
        secret: encryptedStrField("s3cr3t ✓"),
        items: [1, 2.5, null],
      };

      const first = await encoder.encodeNetworkInput(input);
      const second = await encoder.encodeNetworkInput(input);

      expect(first.b64payload).not.toEqual(second.b64payload);
      await expect(encoder.decodeNetworkResult(first)).resolves.toEqual(input);
    },
  );

  it("encrypts only marked fields in partial mode", async () => {
    const encoder = new PayloadEncoder({
      payloadEncryption: { mode: "partial", mainKey: key },
    });

    const encoded = await encoder.encodeNetworkInput({
      user: "alice",
      token: encryptedStrField("s3cr3t"),
    });
    const plaintext = Buffer.from(encoded.b64payload, "base64").toString();

    expect(encoded.encoding_options).toEqual([
      EncodedPayloadOptions.PartiallyEncrypted,
    ]);
    expect(plaintext).toContain("\"user\": \"alice\"");
    expect(plaintext).not.toContain("s3cr3t");
  });

  it("leaves payloads without marked fields unflagged in partial mode", async () => {
    const encoder = new PayloadEncoder({
      payloadEncryption: { mode: "partial", mainKey: key },
    });

    const encoded = await encoder.encodeNetworkInput({ a: 1 });

    expect(encoded.encoding_options).toEqual([]);
    expect(Buffer.from(encoded.b64payload, "base64").toString()).toBe(
      "{\"a\": 1}",
    );
  });

  it("fails to decrypt with the wrong key", async () => {
    const encoded = await new PayloadEncoder({
      payloadEncryption: { mode: "full", mainKey: key },
    }).encodeNetworkInput({ a: 1 });
    const decoder = new PayloadEncoder({
      payloadEncryption: { mode: "full", mainKey: otherKey },
    });

    await expect(decoder.decodeNetworkResult(encoded)).rejects.toThrow(
      WorkflowPayloadEncryptionError,
    );
  });

  it.each([
    ["not hex", "zz".repeat(32)],
    ["odd length", "0".repeat(63)],
    ["wrong size", "00".repeat(20)],
    ["empty", ""],
  ])("rejects an invalid key: %s", (_name, mainKey) => {
    expect(() =>
      new PayloadEncoder({ payloadEncryption: { mode: "full", mainKey } })
    ).toThrow(WorkflowPayloadEncryptionError);
  });

  it.each(["FULL", "fulll", "none", "", null, undefined])(
    "rejects the invalid mode %j instead of sending plaintext",
    (mode) => {
      // Untyped input, e.g. JavaScript or a config parsed from JSON.
      const payloadEncryption = { mode, mainKey: key } as never;

      expect(() => new PayloadEncoder({ payloadEncryption })).toThrow(
        WorkflowPayloadEncryptionError,
      );
    },
  );

  it.each([
    ["no encoding enabled", {}, /payloadEncryption/],
    ["Python-style keys", { payload_encryption: { mode: "full", main_key: key } }, /payload_encryption/],
    ["a null payloadEncryption", { payloadEncryption: null }, /payloadEncryption/],
    ["a non-string key", { payloadEncryption: { mode: "full", mainKey: 123 } }, /mainKey/],
    ["a bigint mode", { payloadEncryption: { mode: 1n, mainKey: key } }, /mode/],
    ["an unknown field", { payloadEncryption: { mode: "full", mainKey: key, extra: 1 } }, /extra/],
  ])("rejects a config with %s instead of sending plaintext", (_name, config, field) => {
    // Untyped input, e.g. JavaScript or a config parsed from JSON.
    expect(() => new PayloadEncoder(config as never)).toThrow(
      WorkflowPayloadEncryptionError,
    );
    expect(() => new PayloadEncoder(config as never)).toThrow(field);
  });

  it("keeps keys out of config errors and of the encoder itself", () => {
    const config = { payloadEncryption: { mode: "FULL", mainKey: key } } as never;
    const error = (() => {
      try {
        new PayloadEncoder(config);
      } catch (e) {
        return e as Error;
      }
    })();
    const encoder = new PayloadEncoder({
      payloadEncryption: { mode: "full", mainKey: key, secondaryKey: otherKey },
    });
    const shown = [
      error?.message,
      inspect(encoder, { depth: Infinity, showHidden: true }),
      JSON.stringify(encoder),
    ].join("\n");

    expect(error?.message).toMatch(/payloadEncryption\.mode/);
    expect(shown).not.toContain(key);
    expect(shown).not.toContain(otherKey);
  });

  it("decodes the NaN and Infinity that Python writes", async () => {
    const encoder = new PayloadEncoder({
      payloadEncryption: { mode: "full", mainKey: key },
    });
    // What pydantic_core.to_json writes for float("inf"), -inf and nan.
    const { data, encodingOptions } = await encoder.encodePayloadContent(
      "{\"score\":Infinity,\"low\":-Infinity,\"ratio\":NaN}",
    );
    const b64payload = Buffer.from(data).toString("base64");
    const expected = { score: Infinity, low: -Infinity, ratio: NaN };

    await expect(
      encoder.decodeNetworkResult({ b64payload, encoding_options: encodingOptions }),
    ).resolves.toEqual(expected);
    await expect(
      encoder.decodeEventPayload({
        type: "json",
        value: b64payload,
        encoding_options: encodingOptions,
      }),
    ).resolves.toMatchObject({ value: expected });
  });

  it("rejects invalid UTF-8 instead of replacing it, like Python", async () => {
    const encoder = new PayloadEncoder({
      payloadEncryption: { mode: "full", mainKey: key },
    });
    // "\xff" is not valid UTF-8.
    const { data, encodingOptions } = await encoder.encodePayloadContent(
      new Uint8Array([0x22, 0xff, 0x22]),
    );
    const b64payload = Buffer.from(data).toString("base64");

    // decode_network_result returns the bytes it can't parse.
    await expect(
      encoder.decodeNetworkResult({ b64payload, encoding_options: encodingOptions }),
    ).resolves.toBeInstanceOf(Uint8Array);
    await expect(
      encoder.decodeEventPayload({
        type: "json",
        value: b64payload,
        encoding_options: encodingOptions,
      }),
    ).rejects.toThrow(TypeError);
    await expect(
      encoder.decodeEventPayload({
        type: "json_patch",
        value: [{ op: "add", path: "/x", value: { type: "__encrypted__", value: b64payload } }],
        encoding_options: [EncodedPayloadOptions.PartiallyEncrypted],
      }),
    ).rejects.toThrow(TypeError);
  });

  it("keeps encrypting if the config's mode is changed afterwards", async () => {
    const payloadEncryption = { mode: "full" as PayloadEncryptionMode, mainKey: key };
    const encoder = new PayloadEncoder({ payloadEncryption });
    payloadEncryption.mode = "invalid" as never;

    const encoded = await encoder.encodeNetworkInput({ a: 1 });

    expect(encoded.encoding_options).toEqual([EncodedPayloadOptions.Encrypted]);
  });

  it("accepts whitespace between key bytes, like bytes.fromhex", () => {
    const spaced = key.match(/../g)!.join(" ");
    expect(() =>
      new PayloadEncoder({ payloadEncryption: { mode: "full", mainKey: spaced } })
    ).not.toThrow();
  });

  describe("in a runtime without 192-bit AES support, like Chromium", () => {
    const aes192 = fixtures.keys["aes192"]!;

    function rejectAes192Keys() {
      const importKey = globalThis.crypto.subtle.importKey.bind(
        globalThis.crypto.subtle,
      );
      vi.spyOn(globalThis.crypto.subtle, "importKey").mockImplementation(
        ((format: "raw", keyData: BufferSource, ...rest: [never, never, never]) =>
          (keyData as Uint8Array).byteLength === 24
            ? Promise.reject(
              new DOMException("AES key data must be 128 or 256 bits", "OperationError"),
            )
            : importKey(format, keyData, ...rest)) as never,
      );
    }

    it("fails to encrypt with a clear error", async () => {
      rejectAes192Keys();
      const encoder = new PayloadEncoder({
        payloadEncryption: { mode: "full", mainKey: aes192 },
      });

      const error = await encoder.encodeNetworkInput({ a: 1 }).catch((e) => e);

      expect(error).toBeInstanceOf(WorkflowPayloadEncryptionError);
      expect(error.message).toMatch(/192-bit/);
      expect(error.cause).toBeInstanceOf(DOMException);
    });

    it("reports the unusable key instead of a failed decryption", async () => {
      const encoded = await new PayloadEncoder({
        payloadEncryption: { mode: "full", mainKey: aes192 },
      }).encodeNetworkInput({ a: 1 });
      rejectAes192Keys();
      const decoder = new PayloadEncoder({
        payloadEncryption: { mode: "full", mainKey: aes192, secondaryKey: key },
      });

      await expect(decoder.decodeNetworkResult(encoded)).rejects.toThrow(/192-bit/);
    });
  });

  it.each([
    [EncodedPayloadOptions.Compressed, WorkflowPayloadCompressionError],
    [EncodedPayloadOptions.Offloaded, WorkflowPayloadOffloadingError],
  ])(
    "rejects %s payloads it can't decode",
    async (option, errorClass) => {
      const encoder = new PayloadEncoder({
        payloadEncryption: { mode: "full", mainKey: key },
      });

      await expect(
        encoder.decodePayloadContent(new Uint8Array([1, 2, 3]), [option]),
      ).rejects.toThrow(errorClass);
    },
  );

  it("returns results that are not encoded as-is", async () => {
    const encoder = new PayloadEncoder({
      payloadEncryption: { mode: "full", mainKey: key },
    });

    await expect(encoder.decodeNetworkResult({ plain: true })).resolves
      .toEqual({ plain: true });
  });
});
