/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 254a218f7d6b
 */

import { ClientSDK } from "../lib/sdks.js";
import { BatchJobs } from "./batchjobs.js";

export class Batch extends ClientSDK {
  private _jobs?: BatchJobs;
  get jobs(): BatchJobs {
    return (this._jobs ??= new BatchJobs(this._options));
  }
}
