/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e85f647437c6
 */

import { betaRagIngestionPipelineConfigurationsList } from "../funcs/betaRagIngestionPipelineConfigurationsList.js";
import { betaRagIngestionPipelineConfigurationsRegister } from "../funcs/betaRagIngestionPipelineConfigurationsRegister.js";
import { betaRagIngestionPipelineConfigurationsUpdateRunInfo } from "../funcs/betaRagIngestionPipelineConfigurationsUpdateRunInfo.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class IngestionPipelineConfigurations extends ClientSDK {
  /**
   * List ingestion pipeline configurations
   *
   * @remarks
   * For the current workspace, lists all of the registered ingestion pipeline configurations.
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<components.IngestionPipelineConfiguration>> {
    return unwrapAsync(betaRagIngestionPipelineConfigurationsList(
      this,
      options,
    ));
  }

  /**
   * Register Config
   *
   * @remarks
   * Register an ingestion configuration.
   */
  async register(
    request: components.CreateIngestionPipelineConfigurationRequest,
    options?: RequestOptions,
  ): Promise<components.IngestionPipelineConfiguration> {
    return unwrapAsync(betaRagIngestionPipelineConfigurationsRegister(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Run Info
   */
  async updateRunInfo(
    request:
      operations.UpdateRunInfoV1RagIngestionPipelineConfigurationsIdRunInfoPutRequest,
    options?: RequestOptions,
  ): Promise<components.IngestionPipelineConfiguration> {
    return unwrapAsync(betaRagIngestionPipelineConfigurationsUpdateRunInfo(
      this,
      request,
      options,
    ));
  }
}
