/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dc7128196075
 */

import { ClientSDK } from "../lib/sdks.js";
import { Sessions } from "./sessions.js";

export class Realtime extends ClientSDK {
  private _sessions?: Sessions;
  get sessions(): Sessions {
    return (this._sessions ??= new Sessions(this._options));
  }
}
