/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TextChunk,
  TextChunk$inboundSchema,
  TextChunk$Outbound,
  TextChunk$outboundSchema,
} from "./textchunk.js";

export type ContentChunk = TextChunk;

/** @internal */
export const ContentChunk$inboundSchema: z.ZodType<
  ContentChunk,
  z.ZodTypeDef,
  unknown
> = TextChunk$inboundSchema;

/** @internal */
export type ContentChunk$Outbound = TextChunk$Outbound;

/** @internal */
export const ContentChunk$outboundSchema: z.ZodType<
  ContentChunk$Outbound,
  z.ZodTypeDef,
  ContentChunk
> = TextChunk$outboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContentChunk$ {
  /** @deprecated use `ContentChunk$inboundSchema` instead. */
  export const inboundSchema = ContentChunk$inboundSchema;
  /** @deprecated use `ContentChunk$outboundSchema` instead. */
  export const outboundSchema = ContentChunk$outboundSchema;
  /** @deprecated use `ContentChunk$Outbound` instead. */
  export type Outbound = ContentChunk$Outbound;
}
