/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8bc5d2f559ed
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ImageDetail = {
  Low: "low",
  Auto: "auto",
  High: "high",
} as const;
export type ImageDetail = OpenEnum<typeof ImageDetail>;

/** @internal */
export const ImageDetail$inboundSchema: z.ZodType<ImageDetail, unknown> =
  openEnums.inboundSchema(ImageDetail);
/** @internal */
export const ImageDetail$outboundSchema: z.ZodType<string, ImageDetail> =
  openEnums.outboundSchema(ImageDetail);
