workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    mistral-azure-source:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-azure:main
        registry:
            location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-azure:main
    mistral-google-cloud-source:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-google-cloud:main
        registry:
            location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi-google-cloud:main
    mistral-openapi:
        inputs:
            - location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi:main
        registry:
            location: registry.speakeasyapi.dev/mistral-dev/mistral-dev/mistral-openapi:main
targets:
    mistralai-azure-sdk:
        target: typescript
        source: mistral-azure-source
        output: ./packages/mistralai-azure
        publish:
            npm:
                token: $npm_token
    mistralai-gcp-sdk:
        target: typescript
        source: mistral-google-cloud-source
        output: ./packages/mistralai-gcp
        publish:
            npm:
                token: $npm_token
    mistralai-sdk:
        target: typescript
        source: mistral-openapi
        publish:
            npm:
                token: $npm_token
