/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5f8e9fb0a895
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ConnectorCreateOrUpdateOrganizationCredentialsV1Request = {
  connectorIdOrName: string;
  credentialsCreateOrUpdate: components.CredentialsCreateOrUpdate;
};

/** @internal */
export type ConnectorCreateOrUpdateOrganizationCredentialsV1Request$Outbound = {
  connector_id_or_name: string;
  CredentialsCreateOrUpdate: components.CredentialsCreateOrUpdate$Outbound;
};

/** @internal */
export const ConnectorCreateOrUpdateOrganizationCredentialsV1Request$outboundSchema:
  z.ZodType<
    ConnectorCreateOrUpdateOrganizationCredentialsV1Request$Outbound,
    ConnectorCreateOrUpdateOrganizationCredentialsV1Request
  > = z.object({
    connectorIdOrName: z.string(),
    credentialsCreateOrUpdate:
      components.CredentialsCreateOrUpdate$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      connectorIdOrName: "connector_id_or_name",
      credentialsCreateOrUpdate: "CredentialsCreateOrUpdate",
    });
  });

export function connectorCreateOrUpdateOrganizationCredentialsV1RequestToJSON(
  connectorCreateOrUpdateOrganizationCredentialsV1Request:
    ConnectorCreateOrUpdateOrganizationCredentialsV1Request,
): string {
  return JSON.stringify(
    ConnectorCreateOrUpdateOrganizationCredentialsV1Request$outboundSchema
      .parse(connectorCreateOrUpdateOrganizationCredentialsV1Request),
  );
}
