/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 69d02864264a
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as components from "../components/index.js";

export const ConnectorCreateCredentialsV1ConsumerScope = {
  User: "user",
  Workspace: "workspace",
  Organization: "organization",
} as const;
export type ConnectorCreateCredentialsV1ConsumerScope = ClosedEnum<
  typeof ConnectorCreateCredentialsV1ConsumerScope
>;

export type ConnectorCreateCredentialsV1Request = {
  connectorIdOrName: string;
  consumerScope: ConnectorCreateCredentialsV1ConsumerScope;
  credentialsCreateOrUpdate: components.CredentialsCreateOrUpdate;
};

/** @internal */
export const ConnectorCreateCredentialsV1ConsumerScope$outboundSchema:
  z.ZodEnum<typeof ConnectorCreateCredentialsV1ConsumerScope> = z.enum(
    ConnectorCreateCredentialsV1ConsumerScope,
  );

/** @internal */
export type ConnectorCreateCredentialsV1Request$Outbound = {
  connector_id_or_name: string;
  consumer_scope: string;
  CredentialsCreateOrUpdate: components.CredentialsCreateOrUpdate$Outbound;
};

/** @internal */
export const ConnectorCreateCredentialsV1Request$outboundSchema: z.ZodType<
  ConnectorCreateCredentialsV1Request$Outbound,
  ConnectorCreateCredentialsV1Request
> = z.object({
  connectorIdOrName: z.string(),
  consumerScope: ConnectorCreateCredentialsV1ConsumerScope$outboundSchema,
  credentialsCreateOrUpdate:
    components.CredentialsCreateOrUpdate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    connectorIdOrName: "connector_id_or_name",
    consumerScope: "consumer_scope",
    credentialsCreateOrUpdate: "CredentialsCreateOrUpdate",
  });
});

export function connectorCreateCredentialsV1RequestToJSON(
  connectorCreateCredentialsV1Request: ConnectorCreateCredentialsV1Request,
): string {
  return JSON.stringify(
    ConnectorCreateCredentialsV1Request$outboundSchema.parse(
      connectorCreateCredentialsV1Request,
    ),
  );
}
