/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 271f18988ce8
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type ConnectorDeleteWorkspaceCredentialsV1Request = {
  credentialsName: string;
  connectorIdOrName: string;
};

/** @internal */
export type ConnectorDeleteWorkspaceCredentialsV1Request$Outbound = {
  credentials_name: string;
  connector_id_or_name: string;
};

/** @internal */
export const ConnectorDeleteWorkspaceCredentialsV1Request$outboundSchema:
  z.ZodType<
    ConnectorDeleteWorkspaceCredentialsV1Request$Outbound,
    ConnectorDeleteWorkspaceCredentialsV1Request
  > = z.object({
    credentialsName: z.string(),
    connectorIdOrName: z.string(),
  }).transform((v) => {
    return remap$(v, {
      credentialsName: "credentials_name",
      connectorIdOrName: "connector_id_or_name",
    });
  });

export function connectorDeleteWorkspaceCredentialsV1RequestToJSON(
  connectorDeleteWorkspaceCredentialsV1Request:
    ConnectorDeleteWorkspaceCredentialsV1Request,
): string {
  return JSON.stringify(
    ConnectorDeleteWorkspaceCredentialsV1Request$outboundSchema.parse(
      connectorDeleteWorkspaceCredentialsV1Request,
    ),
  );
}
