/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0edde8d645f7
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type ConnectorShareV1Request = {
  connectorId: string;
};

/** @internal */
export type ConnectorShareV1Request$Outbound = {
  connector_id: string;
};

/** @internal */
export const ConnectorShareV1Request$outboundSchema: z.ZodType<
  ConnectorShareV1Request$Outbound,
  ConnectorShareV1Request
> = z.object({
  connectorId: z.string(),
}).transform((v) => {
  return remap$(v, {
    connectorId: "connector_id",
  });
});

export function connectorShareV1RequestToJSON(
  connectorShareV1Request: ConnectorShareV1Request,
): string {
  return JSON.stringify(
    ConnectorShareV1Request$outboundSchema.parse(connectorShareV1Request),
  );
}
