/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 731409d55f6b
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type ConnectorShareToOrganizationV1Request = {
  connectorId: string;
};

/** @internal */
export type ConnectorShareToOrganizationV1Request$Outbound = {
  connector_id: string;
};

/** @internal */
export const ConnectorShareToOrganizationV1Request$outboundSchema: z.ZodType<
  ConnectorShareToOrganizationV1Request$Outbound,
  ConnectorShareToOrganizationV1Request
> = z.object({
  connectorId: z.string(),
}).transform((v) => {
  return remap$(v, {
    connectorId: "connector_id",
  });
});

export function connectorShareToOrganizationV1RequestToJSON(
  connectorShareToOrganizationV1Request: ConnectorShareToOrganizationV1Request,
): string {
  return JSON.stringify(
    ConnectorShareToOrganizationV1Request$outboundSchema.parse(
      connectorShareToOrganizationV1Request,
    ),
  );
}
