/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0ef3837f40cb
 */

import * as z from "zod/v4";
import * as components from "../components/index.js";

export type Body = components.CreateRealtimeSessionRequest;

/** @internal */
export type Body$Outbound = components.CreateRealtimeSessionRequest$Outbound;

/** @internal */
export const Body$outboundSchema: z.ZodType<Body$Outbound, Body> =
  components.CreateRealtimeSessionRequest$outboundSchema;

export function bodyToJSON(body: Body): string {
  return JSON.stringify(Body$outboundSchema.parse(body));
}
