/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b2a182d4033b
 */

import * as z from "zod/v4";

export type DeleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest = {
  name: string;
};

/** @internal */
export type DeleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest$Outbound = {
  name: string;
};

/** @internal */
export const DeleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest$outboundSchema:
  z.ZodType<
    DeleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest$Outbound,
    DeleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest
  > = z.object({
    name: z.string(),
  });

export function deleteDeploymentV1WorkflowsDeploymentsNameDeleteRequestToJSON(
  deleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest:
    DeleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest,
): string {
  return JSON.stringify(
    DeleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest$outboundSchema
      .parse(deleteDeploymentV1WorkflowsDeploymentsNameDeleteRequest),
  );
}
