/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 62f752ad882e
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteVoiceV1AudioVoicesVoiceIdDeleteRequest = {
  voiceId: string;
};

/** @internal */
export type DeleteVoiceV1AudioVoicesVoiceIdDeleteRequest$Outbound = {
  voice_id: string;
};

/** @internal */
export const DeleteVoiceV1AudioVoicesVoiceIdDeleteRequest$outboundSchema:
  z.ZodType<
    DeleteVoiceV1AudioVoicesVoiceIdDeleteRequest$Outbound,
    DeleteVoiceV1AudioVoicesVoiceIdDeleteRequest
  > = z.object({
    voiceId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      voiceId: "voice_id",
    });
  });

export function deleteVoiceV1AudioVoicesVoiceIdDeleteRequestToJSON(
  deleteVoiceV1AudioVoicesVoiceIdDeleteRequest:
    DeleteVoiceV1AudioVoicesVoiceIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteVoiceV1AudioVoicesVoiceIdDeleteRequest$outboundSchema.parse(
      deleteVoiceV1AudioVoicesVoiceIdDeleteRequest,
    ),
  );
}
