/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest = {
  /**
   * Dataset UUID or workspace-scoped slug. UUID-shaped values are always interpreted as dataset IDs.
   */
  datasetId: string;
};

/** @internal */
export type GetDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest$Outbound =
  {
    dataset_id: string;
  };

/** @internal */
export const GetDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest$outboundSchema:
  z.ZodType<
    GetDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest$Outbound,
    GetDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest
  > = z.object({
    datasetId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
    });
  });

export function getDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequestToJSON(
  getDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest:
    GetDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest,
): string {
  return JSON.stringify(
    GetDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest$outboundSchema
      .parse(getDatasetByIdV1ObservabilityDatasetsDatasetIdGetRequest),
  );
}
