/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetProjectV1ObservabilityProjectsProjectSlugGetRequest = {
  projectSlug: string;
};

/** @internal */
export type GetProjectV1ObservabilityProjectsProjectSlugGetRequest$Outbound = {
  project_slug: string;
};

/** @internal */
export const GetProjectV1ObservabilityProjectsProjectSlugGetRequest$outboundSchema:
  z.ZodType<
    GetProjectV1ObservabilityProjectsProjectSlugGetRequest$Outbound,
    GetProjectV1ObservabilityProjectsProjectSlugGetRequest
  > = z.object({
    projectSlug: z.string(),
  }).transform((v) => {
    return remap$(v, {
      projectSlug: "project_slug",
    });
  });

export function getProjectV1ObservabilityProjectsProjectSlugGetRequestToJSON(
  getProjectV1ObservabilityProjectsProjectSlugGetRequest:
    GetProjectV1ObservabilityProjectsProjectSlugGetRequest,
): string {
  return JSON.stringify(
    GetProjectV1ObservabilityProjectsProjectSlugGetRequest$outboundSchema.parse(
      getProjectV1ObservabilityProjectsProjectSlugGetRequest,
    ),
  );
}
