/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c3c49cabfde6
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetWorkflowExecutionTraceEventsRequest = {
  executionId: string;
  mergeSameIdEvents?: boolean | undefined;
  includeInternalEvents?: boolean | undefined;
};

/** @internal */
export type GetWorkflowExecutionTraceEventsRequest$Outbound = {
  execution_id: string;
  merge_same_id_events: boolean;
  include_internal_events: boolean;
};

/** @internal */
export const GetWorkflowExecutionTraceEventsRequest$outboundSchema: z.ZodType<
  GetWorkflowExecutionTraceEventsRequest$Outbound,
  GetWorkflowExecutionTraceEventsRequest
> = z.object({
  executionId: z.string(),
  mergeSameIdEvents: z.boolean().default(false),
  includeInternalEvents: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    executionId: "execution_id",
    mergeSameIdEvents: "merge_same_id_events",
    includeInternalEvents: "include_internal_events",
  });
});

export function getWorkflowExecutionTraceEventsRequestToJSON(
  getWorkflowExecutionTraceEventsRequest:
    GetWorkflowExecutionTraceEventsRequest,
): string {
  return JSON.stringify(
    GetWorkflowExecutionTraceEventsRequest$outboundSchema.parse(
      getWorkflowExecutionTraceEventsRequest,
    ),
  );
}
