/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GrepIndexV1RagManagedIndexesIndexNameGrepPostRequest = {
  indexName: string;
  grepRequest: components.GrepRequest;
};

/** @internal */
export type GrepIndexV1RagManagedIndexesIndexNameGrepPostRequest$Outbound = {
  index_name: string;
  GrepRequest: components.GrepRequest$Outbound;
};

/** @internal */
export const GrepIndexV1RagManagedIndexesIndexNameGrepPostRequest$outboundSchema:
  z.ZodType<
    GrepIndexV1RagManagedIndexesIndexNameGrepPostRequest$Outbound,
    GrepIndexV1RagManagedIndexesIndexNameGrepPostRequest
  > = z.object({
    indexName: z.string(),
    grepRequest: components.GrepRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      indexName: "index_name",
      grepRequest: "GrepRequest",
    });
  });

export function grepIndexV1RagManagedIndexesIndexNameGrepPostRequestToJSON(
  grepIndexV1RagManagedIndexesIndexNameGrepPostRequest:
    GrepIndexV1RagManagedIndexesIndexNameGrepPostRequest,
): string {
  return JSON.stringify(
    GrepIndexV1RagManagedIndexesIndexNameGrepPostRequest$outboundSchema.parse(
      grepIndexV1RagManagedIndexesIndexNameGrepPostRequest,
    ),
  );
}
