/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type JobsApiRoutesFineTuningGetFineTuningJobRequest = {
  /**
   * The ID of the job to analyse.
   */
  jobId: string;
};

/** @internal */
export const JobsApiRoutesFineTuningGetFineTuningJobRequest$inboundSchema:
  z.ZodType<
    JobsApiRoutesFineTuningGetFineTuningJobRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    job_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "job_id": "jobId",
    });
  });

/** @internal */
export type JobsApiRoutesFineTuningGetFineTuningJobRequest$Outbound = {
  job_id: string;
};

/** @internal */
export const JobsApiRoutesFineTuningGetFineTuningJobRequest$outboundSchema:
  z.ZodType<
    JobsApiRoutesFineTuningGetFineTuningJobRequest$Outbound,
    z.ZodTypeDef,
    JobsApiRoutesFineTuningGetFineTuningJobRequest
  > = z.object({
    jobId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      jobId: "job_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace JobsApiRoutesFineTuningGetFineTuningJobRequest$ {
  /** @deprecated use `JobsApiRoutesFineTuningGetFineTuningJobRequest$inboundSchema` instead. */
  export const inboundSchema =
    JobsApiRoutesFineTuningGetFineTuningJobRequest$inboundSchema;
  /** @deprecated use `JobsApiRoutesFineTuningGetFineTuningJobRequest$outboundSchema` instead. */
  export const outboundSchema =
    JobsApiRoutesFineTuningGetFineTuningJobRequest$outboundSchema;
  /** @deprecated use `JobsApiRoutesFineTuningGetFineTuningJobRequest$Outbound` instead. */
  export type Outbound =
    JobsApiRoutesFineTuningGetFineTuningJobRequest$Outbound;
}

export function jobsApiRoutesFineTuningGetFineTuningJobRequestToJSON(
  jobsApiRoutesFineTuningGetFineTuningJobRequest:
    JobsApiRoutesFineTuningGetFineTuningJobRequest,
): string {
  return JSON.stringify(
    JobsApiRoutesFineTuningGetFineTuningJobRequest$outboundSchema.parse(
      jobsApiRoutesFineTuningGetFineTuningJobRequest,
    ),
  );
}

export function jobsApiRoutesFineTuningGetFineTuningJobRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  JobsApiRoutesFineTuningGetFineTuningJobRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      JobsApiRoutesFineTuningGetFineTuningJobRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'JobsApiRoutesFineTuningGetFineTuningJobRequest' from JSON`,
  );
}
