/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7a9a3b1cfb1c
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest =
  {
    serviceAccountId: string;
  };

/** @internal */
export type ListServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest$Outbound =
  {
    service_account_id: string;
  };

/** @internal */
export const ListServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest$outboundSchema:
  z.ZodType<
    ListServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest$Outbound,
    ListServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest
  > = z.object({
    serviceAccountId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      serviceAccountId: "service_account_id",
    });
  });

export function listServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequestToJSON(
  listServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest:
    ListServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest,
): string {
  return JSON.stringify(
    ListServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest$outboundSchema
      .parse(
        listServiceAccountRolesV1ServiceAccountsServiceAccountIdRolesGetRequest,
      ),
  );
}
