/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type PostDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest =
  {
    /**
     * Dataset UUID or workspace-scoped slug. UUID-shaped values are always interpreted as dataset IDs.
     */
    datasetId: string;
    importDatasetFromSpansRequest: components.ImportDatasetFromSpansRequest;
  };

/** @internal */
export type PostDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest$Outbound =
  {
    dataset_id: string;
    ImportDatasetFromSpansRequest:
      components.ImportDatasetFromSpansRequest$Outbound;
  };

/** @internal */
export const PostDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest$outboundSchema:
  z.ZodType<
    PostDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest$Outbound,
    PostDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest
  > = z.object({
    datasetId: z.string(),
    importDatasetFromSpansRequest:
      components.ImportDatasetFromSpansRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      importDatasetFromSpansRequest: "ImportDatasetFromSpansRequest",
    });
  });

export function postDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequestToJSON(
  postDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest:
    PostDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest,
): string {
  return JSON.stringify(
    PostDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest$outboundSchema
      .parse(
        postDatasetRecordsFromSpansV1ObservabilityDatasetsDatasetIdImportsFromSpansPostRequest,
      ),
  );
}
