/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 69938506ae81
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type SetSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest =
  {
    indexId: string;
    schemaId: string;
    updateSchemaSummaryRequestSummary:
      components.UpdateSchemaSummaryRequestSummary;
  };

/** @internal */
export type SetSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest$Outbound =
  {
    index_id: string;
    schema_id: string;
    UpdateSchemaSummaryRequestSummary:
      components.UpdateSchemaSummaryRequestSummary$Outbound;
  };

/** @internal */
export const SetSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest$outboundSchema:
  z.ZodType<
    SetSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest$Outbound,
    SetSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest
  > = z.object({
    indexId: z.string(),
    schemaId: z.string(),
    updateSchemaSummaryRequestSummary:
      components.UpdateSchemaSummaryRequestSummary$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      indexId: "index_id",
      schemaId: "schema_id",
      updateSchemaSummaryRequestSummary: "UpdateSchemaSummaryRequestSummary",
    });
  });

export function setSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequestToJSON(
  setSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest:
    SetSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest,
): string {
  return JSON.stringify(
    SetSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest$outboundSchema
      .parse(
        setSchemaSummaryV1RagIndexesIndexIndexIdSchemasSchemaSchemaIdSummaryFieldPutRequest,
      ),
  );
}
