/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 13b6eb0d431d
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest =
  {
    executionId: string;
    signalInvocationBody: components.SignalInvocationBody;
  };

/** @internal */
export type SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest$Outbound =
  {
    execution_id: string;
    SignalInvocationBody: components.SignalInvocationBody$Outbound;
  };

/** @internal */
export const SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest$outboundSchema:
  z.ZodType<
    SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest$Outbound,
    SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest
  > = z.object({
    executionId: z.string(),
    signalInvocationBody: components.SignalInvocationBody$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      executionId: "execution_id",
      signalInvocationBody: "SignalInvocationBody",
    });
  });

export function signalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequestToJSON(
  signalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest:
    SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest,
): string {
  return JSON.stringify(
    SignalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest$outboundSchema
      .parse(
        signalWorkflowExecutionV1WorkflowsExecutionsExecutionIdSignalsPostRequest,
      ),
  );
}
