/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 80f331d6ec5f
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type SkillsListVersionsRequest = {
  skillId: string;
};

/** @internal */
export type SkillsListVersionsRequest$Outbound = {
  skill_id: string;
};

/** @internal */
export const SkillsListVersionsRequest$outboundSchema: z.ZodType<
  SkillsListVersionsRequest$Outbound,
  SkillsListVersionsRequest
> = z.object({
  skillId: z.string(),
}).transform((v) => {
  return remap$(v, {
    skillId: "skill_id",
  });
});

export function skillsListVersionsRequestToJSON(
  skillsListVersionsRequest: SkillsListVersionsRequest,
): string {
  return JSON.stringify(
    SkillsListVersionsRequest$outboundSchema.parse(skillsListVersionsRequest),
  );
}
