/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest = {
  /**
   * Dataset UUID or workspace-scoped slug. UUID-shaped values are always interpreted as dataset IDs.
   */
  datasetId: string;
  updateDatasetRequest: components.UpdateDatasetRequest;
};

/** @internal */
export type UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest$Outbound =
  {
    dataset_id: string;
    UpdateDatasetRequest: components.UpdateDatasetRequest$Outbound;
  };

/** @internal */
export const UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest$outboundSchema:
  z.ZodType<
    UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest$Outbound,
    UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest
  > = z.object({
    datasetId: z.string(),
    updateDatasetRequest: components.UpdateDatasetRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      updateDatasetRequest: "UpdateDatasetRequest",
    });
  });

export function updateDatasetV1ObservabilityDatasetsDatasetIdPatchRequestToJSON(
  updateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest:
    UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest,
): string {
  return JSON.stringify(
    UpdateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest$outboundSchema
      .parse(updateDatasetV1ObservabilityDatasetsDatasetIdPatchRequest),
  );
}
