/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 646c7c0040d9
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateDeploymentV1WorkflowsDeploymentsNamePatchRequest = {
  name: string;
  updateDeploymentRequest: components.UpdateDeploymentRequest;
};

/** @internal */
export type UpdateDeploymentV1WorkflowsDeploymentsNamePatchRequest$Outbound = {
  name: string;
  UpdateDeploymentRequest: components.UpdateDeploymentRequest$Outbound;
};

/** @internal */
export const UpdateDeploymentV1WorkflowsDeploymentsNamePatchRequest$outboundSchema:
  z.ZodType<
    UpdateDeploymentV1WorkflowsDeploymentsNamePatchRequest$Outbound,
    UpdateDeploymentV1WorkflowsDeploymentsNamePatchRequest
  > = z.object({
    name: z.string(),
    updateDeploymentRequest: components.UpdateDeploymentRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      updateDeploymentRequest: "UpdateDeploymentRequest",
    });
  });

export function updateDeploymentV1WorkflowsDeploymentsNamePatchRequestToJSON(
  updateDeploymentV1WorkflowsDeploymentsNamePatchRequest:
    UpdateDeploymentV1WorkflowsDeploymentsNamePatchRequest,
): string {
  return JSON.stringify(
    UpdateDeploymentV1WorkflowsDeploymentsNamePatchRequest$outboundSchema.parse(
      updateDeploymentV1WorkflowsDeploymentsNamePatchRequest,
    ),
  );
}
