/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1LibrariesGetRequest = {
  libraryId: string;
};

/** @internal */
export const V1LibrariesGetRequest$inboundSchema: z.ZodType<
  V1LibrariesGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  library_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "library_id": "libraryId",
  });
});

/** @internal */
export type V1LibrariesGetRequest$Outbound = {
  library_id: string;
};

/** @internal */
export const V1LibrariesGetRequest$outboundSchema: z.ZodType<
  V1LibrariesGetRequest$Outbound,
  z.ZodTypeDef,
  V1LibrariesGetRequest
> = z.object({
  libraryId: z.string(),
}).transform((v) => {
  return remap$(v, {
    libraryId: "library_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1LibrariesGetRequest$ {
  /** @deprecated use `V1LibrariesGetRequest$inboundSchema` instead. */
  export const inboundSchema = V1LibrariesGetRequest$inboundSchema;
  /** @deprecated use `V1LibrariesGetRequest$outboundSchema` instead. */
  export const outboundSchema = V1LibrariesGetRequest$outboundSchema;
  /** @deprecated use `V1LibrariesGetRequest$Outbound` instead. */
  export type Outbound = V1LibrariesGetRequest$Outbound;
}

export function v1LibrariesGetRequestToJSON(
  v1LibrariesGetRequest: V1LibrariesGetRequest,
): string {
  return JSON.stringify(
    V1LibrariesGetRequest$outboundSchema.parse(v1LibrariesGetRequest),
  );
}

export function v1LibrariesGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1LibrariesGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1LibrariesGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1LibrariesGetRequest' from JSON`,
  );
}
