/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1LibrariesDocumentsGetRequest = {
  libraryId: string;
  documentId: string;
};

/** @internal */
export const V1LibrariesDocumentsGetRequest$inboundSchema: z.ZodType<
  V1LibrariesDocumentsGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  library_id: z.string(),
  document_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "library_id": "libraryId",
    "document_id": "documentId",
  });
});

/** @internal */
export type V1LibrariesDocumentsGetRequest$Outbound = {
  library_id: string;
  document_id: string;
};

/** @internal */
export const V1LibrariesDocumentsGetRequest$outboundSchema: z.ZodType<
  V1LibrariesDocumentsGetRequest$Outbound,
  z.ZodTypeDef,
  V1LibrariesDocumentsGetRequest
> = z.object({
  libraryId: z.string(),
  documentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    libraryId: "library_id",
    documentId: "document_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1LibrariesDocumentsGetRequest$ {
  /** @deprecated use `V1LibrariesDocumentsGetRequest$inboundSchema` instead. */
  export const inboundSchema = V1LibrariesDocumentsGetRequest$inboundSchema;
  /** @deprecated use `V1LibrariesDocumentsGetRequest$outboundSchema` instead. */
  export const outboundSchema = V1LibrariesDocumentsGetRequest$outboundSchema;
  /** @deprecated use `V1LibrariesDocumentsGetRequest$Outbound` instead. */
  export type Outbound = V1LibrariesDocumentsGetRequest$Outbound;
}

export function v1LibrariesDocumentsGetRequestToJSON(
  v1LibrariesDocumentsGetRequest: V1LibrariesDocumentsGetRequest,
): string {
  return JSON.stringify(
    V1LibrariesDocumentsGetRequest$outboundSchema.parse(
      v1LibrariesDocumentsGetRequest,
    ),
  );
}

export function v1LibrariesDocumentsGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1LibrariesDocumentsGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1LibrariesDocumentsGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1LibrariesDocumentsGetRequest' from JSON`,
  );
}
