/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1LibrariesShareDeleteRequest = {
  libraryId: string;
  sharingDelete: components.SharingDelete;
};

/** @internal */
export const V1LibrariesShareDeleteRequest$inboundSchema: z.ZodType<
  V1LibrariesShareDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  library_id: z.string(),
  SharingDelete: components.SharingDelete$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "library_id": "libraryId",
    "SharingDelete": "sharingDelete",
  });
});

/** @internal */
export type V1LibrariesShareDeleteRequest$Outbound = {
  library_id: string;
  SharingDelete: components.SharingDelete$Outbound;
};

/** @internal */
export const V1LibrariesShareDeleteRequest$outboundSchema: z.ZodType<
  V1LibrariesShareDeleteRequest$Outbound,
  z.ZodTypeDef,
  V1LibrariesShareDeleteRequest
> = z.object({
  libraryId: z.string(),
  sharingDelete: components.SharingDelete$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    libraryId: "library_id",
    sharingDelete: "SharingDelete",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1LibrariesShareDeleteRequest$ {
  /** @deprecated use `V1LibrariesShareDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = V1LibrariesShareDeleteRequest$inboundSchema;
  /** @deprecated use `V1LibrariesShareDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = V1LibrariesShareDeleteRequest$outboundSchema;
  /** @deprecated use `V1LibrariesShareDeleteRequest$Outbound` instead. */
  export type Outbound = V1LibrariesShareDeleteRequest$Outbound;
}

export function v1LibrariesShareDeleteRequestToJSON(
  v1LibrariesShareDeleteRequest: V1LibrariesShareDeleteRequest,
): string {
  return JSON.stringify(
    V1LibrariesShareDeleteRequest$outboundSchema.parse(
      v1LibrariesShareDeleteRequest,
    ),
  );
}

export function v1LibrariesShareDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1LibrariesShareDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1LibrariesShareDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1LibrariesShareDeleteRequest' from JSON`,
  );
}
