/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c4d645d9bce2
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AggregationMeta,
  AggregationMeta$inboundSchema,
} from "./aggregationmeta.js";
import {
  AggregationRow,
  AggregationRow$inboundSchema,
} from "./aggregationrow.js";

export type Aggregation = {
  data: Array<AggregationRow>;
  meta: AggregationMeta;
};

/** @internal */
export const Aggregation$inboundSchema: z.ZodType<Aggregation, unknown> = z
  .object({
    data: z.array(AggregationRow$inboundSchema),
    meta: AggregationMeta$inboundSchema,
  });

export function aggregationFromJSON(
  jsonString: string,
): SafeParseResult<Aggregation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Aggregation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Aggregation' from JSON`,
  );
}
