/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aa35170263e3
 */

import * as z from "zod/v4";

export type APIKeyAuth = {
  type: "api-key";
  value: string;
};

/** @internal */
export type APIKeyAuth$Outbound = {
  type: "api-key";
  value: string;
};

/** @internal */
export const APIKeyAuth$outboundSchema: z.ZodType<
  APIKeyAuth$Outbound,
  APIKeyAuth
> = z.object({
  type: z.literal("api-key"),
  value: z.string(),
});

export function apiKeyAuthToJSON(apiKeyAuth: APIKeyAuth): string {
  return JSON.stringify(APIKeyAuth$outboundSchema.parse(apiKeyAuth));
}
