/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 905a70dfea53
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Annotations, Annotations$inboundSchema } from "./annotations.js";

/**
 * Audio content for a message.
 */
export type AudioContent = {
  type: "audio";
  data: string;
  mimeType: string;
  annotations?: Annotations | null | undefined;
  meta?: { [k: string]: any } | null | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const AudioContent$inboundSchema: z.ZodType<AudioContent, unknown> = z
  .object({
    type: z.literal("audio"),
    data: z.string(),
    mimeType: z.string(),
    annotations: z.nullable(Annotations$inboundSchema).optional(),
    _meta: z.nullable(z.record(z.string(), z.any())).optional(),
  }).catchall(z.any()).transform((v) => {
    return remap$(v, {
      "_meta": "meta",
    });
  });

export function audioContentFromJSON(
  jsonString: string,
): SafeParseResult<AudioContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AudioContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AudioContent' from JSON`,
  );
}
