/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d3ba45946d1c
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BoolArrayFieldDefinition = {
  type: "bool[]";
  indexed?: boolean | undefined;
  required?: boolean | undefined;
  system?: boolean | undefined;
  default?: any | null | undefined;
};

/** @internal */
export const BoolArrayFieldDefinition$inboundSchema: z.ZodType<
  BoolArrayFieldDefinition,
  unknown
> = z.object({
  type: z.literal("bool[]"),
  indexed: z.boolean().default(false),
  required: z.boolean().default(false),
  system: z.boolean().default(false),
  default: z.nullable(z.any()).optional(),
});
/** @internal */
export type BoolArrayFieldDefinition$Outbound = {
  type: "bool[]";
  indexed: boolean;
  required: boolean;
  system: boolean;
  default?: any | null | undefined;
};

/** @internal */
export const BoolArrayFieldDefinition$outboundSchema: z.ZodType<
  BoolArrayFieldDefinition$Outbound,
  BoolArrayFieldDefinition
> = z.object({
  type: z.literal("bool[]"),
  indexed: z.boolean().default(false),
  required: z.boolean().default(false),
  system: z.boolean().default(false),
  default: z.nullable(z.any()).optional(),
});

export function boolArrayFieldDefinitionToJSON(
  boolArrayFieldDefinition: BoolArrayFieldDefinition,
): string {
  return JSON.stringify(
    BoolArrayFieldDefinition$outboundSchema.parse(boolArrayFieldDefinition),
  );
}
export function boolArrayFieldDefinitionFromJSON(
  jsonString: string,
): SafeParseResult<BoolArrayFieldDefinition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BoolArrayFieldDefinition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BoolArrayFieldDefinition' from JSON`,
  );
}
