/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: de5bf5542528
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ConnectorProtocol = {
  Mcp: "mcp",
  Http: "http",
  Turbine: "turbine",
} as const;
export type ConnectorProtocol = OpenEnum<typeof ConnectorProtocol>;

/** @internal */
export const ConnectorProtocol$inboundSchema: z.ZodType<
  ConnectorProtocol,
  unknown
> = openEnums.inboundSchema(ConnectorProtocol);
