/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a3c3f908ad8a
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminatedUnion.js";
import { discriminatedUnion } from "../../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { HTTPConnector, HTTPConnector$inboundSchema } from "./httpconnector.js";
import { MCPConnector, MCPConnector$inboundSchema } from "./mcpconnector.js";

export type Connector =
  | HTTPConnector
  | MCPConnector
  | discriminatedUnionTypes.Unknown<"protocol">;

/** @internal */
export const Connector$inboundSchema: z.ZodType<Connector, unknown> =
  discriminatedUnion("protocol", {
    http: HTTPConnector$inboundSchema,
    mcp: MCPConnector$inboundSchema,
  });

export function connectorFromJSON(
  jsonString: string,
): SafeParseResult<Connector, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Connector$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Connector' from JSON`,
  );
}
