/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f70ff8bdb149
 */

import * as z from "zod/v4";

/**
 * Request body for calling an MCP tool.
 */
export type ConnectorCallToolRequest = {
  arguments?: { [k: string]: any } | undefined;
};

/** @internal */
export type ConnectorCallToolRequest$Outbound = {
  arguments?: { [k: string]: any } | undefined;
};

/** @internal */
export const ConnectorCallToolRequest$outboundSchema: z.ZodType<
  ConnectorCallToolRequest$Outbound,
  ConnectorCallToolRequest
> = z.object({
  arguments: z.record(z.string(), z.any()).optional(),
});

export function connectorCallToolRequestToJSON(
  connectorCallToolRequest: ConnectorCallToolRequest,
): string {
  return JSON.stringify(
    ConnectorCallToolRequest$outboundSchema.parse(connectorCallToolRequest),
  );
}
