/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aa94d49ee354
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  ConversationPayload,
  ConversationPayload$Outbound,
  ConversationPayload$outboundSchema,
} from "./conversationpayload.js";

export type CreateDatasetRecordRequest = {
  conversationPayload: ConversationPayload;
  properties: { [k: string]: any };
};

/** @internal */
export type CreateDatasetRecordRequest$Outbound = {
  payload: ConversationPayload$Outbound;
  properties: { [k: string]: any };
};

/** @internal */
export const CreateDatasetRecordRequest$outboundSchema: z.ZodType<
  CreateDatasetRecordRequest$Outbound,
  CreateDatasetRecordRequest
> = z.object({
  conversationPayload: ConversationPayload$outboundSchema,
  properties: z.record(z.string(), z.any()),
}).transform((v) => {
  return remap$(v, {
    conversationPayload: "payload",
  });
});

export function createDatasetRecordRequestToJSON(
  createDatasetRecordRequest: CreateDatasetRecordRequest,
): string {
  return JSON.stringify(
    CreateDatasetRecordRequest$outboundSchema.parse(createDatasetRecordRequest),
  );
}
