/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c81f98a8ce78
 */

import * as z from "zod/v4";

export type CreateIngestionPipelineConfigurationRequest = {
  name: string;
};

/** @internal */
export type CreateIngestionPipelineConfigurationRequest$Outbound = {
  name: string;
};

/** @internal */
export const CreateIngestionPipelineConfigurationRequest$outboundSchema:
  z.ZodType<
    CreateIngestionPipelineConfigurationRequest$Outbound,
    CreateIngestionPipelineConfigurationRequest
  > = z.object({
    name: z.string(),
  });

export function createIngestionPipelineConfigurationRequestToJSON(
  createIngestionPipelineConfigurationRequest:
    CreateIngestionPipelineConfigurationRequest,
): string {
  return JSON.stringify(
    CreateIngestionPipelineConfigurationRequest$outboundSchema.parse(
      createIngestionPipelineConfigurationRequest,
    ),
  );
}
