/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d3f5a3ca2e49
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreatePromptVersionResponse = {
  version?: number | undefined;
  deduplicated?: boolean | undefined;
};

/** @internal */
export const CreatePromptVersionResponse$inboundSchema: z.ZodType<
  CreatePromptVersionResponse,
  unknown
> = z.object({
  version: z.int().optional(),
  deduplicated: z.boolean().optional(),
});

export function createPromptVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePromptVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePromptVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePromptVersionResponse' from JSON`,
  );
}
