/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7342cdd00079
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CustomTaskStartedAttributesRequest,
  CustomTaskStartedAttributesRequest$Outbound,
  CustomTaskStartedAttributesRequest$outboundSchema,
} from "./customtaskstartedattributesrequest.js";

/**
 * Emitted when a custom task begins execution.
 *
 * @remarks
 *
 * Custom tasks represent user-defined units of work within a workflow,
 * such as LLM calls, API requests, or data processing steps.
 */
export type CustomTaskStartedRequest = {
  /**
   * Unique identifier for this event instance.
   */
  eventId: string;
  /**
   * Unix timestamp in nanoseconds when the event was created.
   */
  eventTimestamp?: number | undefined;
  /**
   * Execution ID of the root workflow that initiated this execution chain.
   */
  rootWorkflowExecId: string;
  /**
   * Execution ID of the parent workflow that initiated this execution. If this is a root workflow, this field is not set.
   */
  parentWorkflowExecId?: string | null | undefined;
  /**
   * Execution ID of the workflow that emitted this event.
   */
  workflowExecId: string;
  /**
   * Run ID of the workflow execution. Changes on continue-as-new while workflow_exec_id stays the same.
   */
  workflowRunId: string;
  /**
   * The registered name of the workflow that emitted this event.
   */
  workflowName: string;
  /**
   * Event type discriminator.
   */
  eventType?: "CUSTOM_TASK_STARTED" | undefined;
  /**
   * Attributes for custom task started events.
   */
  attributes: CustomTaskStartedAttributesRequest;
};

/** @internal */
export type CustomTaskStartedRequest$Outbound = {
  event_id: string;
  event_timestamp?: number | undefined;
  root_workflow_exec_id: string;
  parent_workflow_exec_id?: string | null | undefined;
  workflow_exec_id: string;
  workflow_run_id: string;
  workflow_name: string;
  event_type: "CUSTOM_TASK_STARTED";
  attributes: CustomTaskStartedAttributesRequest$Outbound;
};

/** @internal */
export const CustomTaskStartedRequest$outboundSchema: z.ZodType<
  CustomTaskStartedRequest$Outbound,
  CustomTaskStartedRequest
> = z.object({
  eventId: z.string(),
  eventTimestamp: z.int().optional(),
  rootWorkflowExecId: z.string(),
  parentWorkflowExecId: z.nullable(z.string()).optional(),
  workflowExecId: z.string(),
  workflowRunId: z.string(),
  workflowName: z.string(),
  eventType: z.literal("CUSTOM_TASK_STARTED").default(
    "CUSTOM_TASK_STARTED" as const,
  ),
  attributes: CustomTaskStartedAttributesRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    eventId: "event_id",
    eventTimestamp: "event_timestamp",
    rootWorkflowExecId: "root_workflow_exec_id",
    parentWorkflowExecId: "parent_workflow_exec_id",
    workflowExecId: "workflow_exec_id",
    workflowRunId: "workflow_run_id",
    workflowName: "workflow_name",
    eventType: "event_type",
  });
});

export function customTaskStartedRequestToJSON(
  customTaskStartedRequest: CustomTaskStartedRequest,
): string {
  return JSON.stringify(
    CustomTaskStartedRequest$outboundSchema.parse(customTaskStartedRequest),
  );
}
