/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9cfe08b0a9dc
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteBatchJobResponse = {
  id: string;
  object: "batch";
  deleted: boolean;
};

/** @internal */
export const DeleteBatchJobResponse$inboundSchema: z.ZodType<
  DeleteBatchJobResponse,
  unknown
> = z.object({
  id: z.string(),
  object: z.literal("batch").default("batch"),
  deleted: z.boolean().default(true),
});

export function deleteBatchJobResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteBatchJobResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteBatchJobResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteBatchJobResponse' from JSON`,
  );
}
