/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2475e27b5531
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteSkillResponse = {};

/** @internal */
export const DeleteSkillResponse$inboundSchema: z.ZodType<
  DeleteSkillResponse,
  unknown
> = z.object({});

export function deleteSkillResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSkillResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSkillResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSkillResponse' from JSON`,
  );
}
