/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ManagedIndexStatus,
  ManagedIndexStatus$inboundSchema,
} from "./managedindexstatus.js";

/**
 * Wire representation returned when an index is deleted (id, name, status).
 */
export type DeleteManagedIndexResponse = {
  id: string;
  name: string;
  /**
   * Lifecycle of an index. Derived, not stored -- see ``managed_index_from_row``.
   */
  status: ManagedIndexStatus;
};

/** @internal */
export const DeleteManagedIndexResponse$inboundSchema: z.ZodType<
  DeleteManagedIndexResponse,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  status: ManagedIndexStatus$inboundSchema,
});

export function deleteManagedIndexResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteManagedIndexResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteManagedIndexResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteManagedIndexResponse' from JSON`,
  );
}
