/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dcc72a7744f5
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteDocumentsRequest = {
  documentIds: Array<string>;
};

/** @internal */
export type DeleteDocumentsRequest$Outbound = {
  document_ids: Array<string>;
};

/** @internal */
export const DeleteDocumentsRequest$outboundSchema: z.ZodType<
  DeleteDocumentsRequest$Outbound,
  DeleteDocumentsRequest
> = z.object({
  documentIds: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    documentIds: "document_ids",
  });
});

export function deleteDocumentsRequestToJSON(
  deleteDocumentsRequest: DeleteDocumentsRequest,
): string {
  return JSON.stringify(
    DeleteDocumentsRequest$outboundSchema.parse(deleteDocumentsRequest),
  );
}
