/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ddcf1766ad74
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DeploymentLocation,
  DeploymentLocation$inboundSchema,
} from "./deploymentlocation.js";
import {
  DeploymentWorkerResponse,
  DeploymentWorkerResponse$inboundSchema,
} from "./deploymentworkerresponse.js";
import { LocationType, LocationType$inboundSchema } from "./locationtype.js";
import {
  ManagedDeploymentResponse,
  ManagedDeploymentResponse$inboundSchema,
} from "./manageddeploymentresponse.js";

export type DeploymentDetailResponse = {
  /**
   * Unique identifier of the deployment
   */
  id: string;
  /**
   * Deployment name
   */
  name: string;
  /**
   * Whether at least one worker is currently live
   */
  isActive: boolean;
  /**
   * Whether the deployment has at least one authorized credential
   */
  isHardened: boolean;
  /**
   * When the deployment was first registered
   */
  createdAt: Date;
  /**
   * When the deployment was last updated
   */
  updatedAt: Date;
  /**
   * Where the deployment is running
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  location?: DeploymentLocation | null | undefined;
  /**
   * Number of workers registered to the deployment
   */
  workerCount: number;
  /**
   * Number of workers currently live within the liveness cutoff
   */
  activeWorkerCount: number;
  /**
   * Distinct location types reported by the deployment's workers
   */
  locations?: Array<LocationType> | undefined;
  /**
   * Live managed service state for managed deployments; null for self-hosted deployments or when managed services are unavailable
   */
  managed?: ManagedDeploymentResponse | null | undefined;
  /**
   * Workers registered for the deployment
   */
  workers: Array<DeploymentWorkerResponse>;
};

/** @internal */
export const DeploymentDetailResponse$inboundSchema: z.ZodType<
  DeploymentDetailResponse,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  is_active: z.boolean(),
  is_hardened: z.boolean().default(false),
  created_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  location: z.nullable(DeploymentLocation$inboundSchema).optional(),
  worker_count: z.int().default(0),
  active_worker_count: z.int().default(0),
  locations: z.array(LocationType$inboundSchema).optional(),
  managed: z.nullable(ManagedDeploymentResponse$inboundSchema).optional(),
  workers: z.array(DeploymentWorkerResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "is_active": "isActive",
    "is_hardened": "isHardened",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "worker_count": "workerCount",
    "active_worker_count": "activeWorkerCount",
  });
});

export function deploymentDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentDetailResponse' from JSON`,
  );
}
