/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dcfbdb9d9f94
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeploymentWorkerSpecResponse = {
  githubUrl: string;
  type: string;
  revision?: string | null | undefined;
  entrypoint?: string | null | undefined;
  workingDir?: string | null | undefined;
  restartedAt?: string | null | undefined;
  commitSha?: string | null | undefined;
};

/** @internal */
export const DeploymentWorkerSpecResponse$inboundSchema: z.ZodType<
  DeploymentWorkerSpecResponse,
  unknown
> = z.object({
  github_url: z.string(),
  type: z.string().default("workflows_worker"),
  revision: z.nullable(z.string()).optional(),
  entrypoint: z.nullable(z.string()).optional(),
  working_dir: z.nullable(z.string()).optional(),
  restarted_at: z.nullable(z.string()).optional(),
  commit_sha: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "github_url": "githubUrl",
    "working_dir": "workingDir",
    "restarted_at": "restartedAt",
    "commit_sha": "commitSha",
  });
});

export function deploymentWorkerSpecResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentWorkerSpecResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentWorkerSpecResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentWorkerSpecResponse' from JSON`,
  );
}
