/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EvaluationRunGenerationV2,
  EvaluationRunGenerationV2$inboundSchema,
} from "./evaluationrungenerationv2.js";
import {
  EvaluatorStatistics,
  EvaluatorStatistics$inboundSchema,
} from "./evaluatorstatistics.js";
import { GoalResult, GoalResult$inboundSchema } from "./goalresult.js";

export type EvaluationRunOutputRecordV2 = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  metadata: { [k: string]: any };
  recordInfo?: { [k: string]: any } | null | undefined;
  generations?: Array<EvaluationRunGenerationV2> | undefined;
  statistics?: { [k: string]: EvaluatorStatistics } | undefined;
  goalResults?: { [k: string]: GoalResult } | undefined;
};

/** @internal */
export const EvaluationRunOutputRecordV2$inboundSchema: z.ZodType<
  EvaluationRunOutputRecordV2,
  unknown
> = z.object({
  id: z.string(),
  created_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  deleted_at: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ),
  metadata_: z.record(z.string(), z.any()),
  record_info: z.nullable(z.record(z.string(), z.any())).optional(),
  generations: z.array(EvaluationRunGenerationV2$inboundSchema).optional(),
  statistics: z.record(z.string(), EvaluatorStatistics$inboundSchema)
    .optional(),
  goal_results: z.record(z.string(), GoalResult$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "deleted_at": "deletedAt",
    "metadata_": "metadata",
    "record_info": "recordInfo",
    "goal_results": "goalResults",
  });
});

export function evaluationRunOutputRecordV2FromJSON(
  jsonString: string,
): SafeParseResult<EvaluationRunOutputRecordV2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvaluationRunOutputRecordV2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvaluationRunOutputRecordV2' from JSON`,
  );
}
