/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EvaluationRunScoreV2,
  EvaluationRunScoreV2$inboundSchema,
} from "./evaluationrunscorev2.js";
import {
  EvaluatorStatistics,
  EvaluatorStatistics$inboundSchema,
} from "./evaluatorstatistics.js";
import { EvaluatorV2, EvaluatorV2$inboundSchema } from "./evaluatorv2.js";
import { GoalResult, GoalResult$inboundSchema } from "./goalresult.js";
import {
  RunEvaluationSummary,
  RunEvaluationSummary$inboundSchema,
} from "./runevaluationsummary.js";
import {
  RunOptimizationRef,
  RunOptimizationRef$inboundSchema,
} from "./runoptimizationref.js";
import {
  RunProjectSummary,
  RunProjectSummary$inboundSchema,
} from "./runprojectsummary.js";
import { SystemV2, SystemV2$inboundSchema } from "./systemv2.js";

export type EvaluationRunV2WithRefsResponse = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  creatorId: string;
  evaluationId: string;
  name: string;
  description: string | null;
  tags: Array<string>;
  metadata: { [k: string]: any };
  numGenerations: number;
  runInfo?: { [k: string]: any } | null | undefined;
  status: string;
  datasetId?: string | null | undefined;
  evaluators: Array<EvaluatorV2>;
  runEvaluators?: Array<EvaluatorV2> | undefined;
  system?: SystemV2 | null | undefined;
  statistics?: { [k: string]: EvaluatorStatistics } | undefined;
  goalResults?: { [k: string]: GoalResult } | undefined;
  passed?: boolean | null | undefined;
  runScores?: { [k: string]: EvaluationRunScoreV2 } | undefined;
  optimization?: RunOptimizationRef | null | undefined;
  evaluation?: RunEvaluationSummary | null | undefined;
  project?: RunProjectSummary | null | undefined;
};

/** @internal */
export const EvaluationRunV2WithRefsResponse$inboundSchema: z.ZodType<
  EvaluationRunV2WithRefsResponse,
  unknown
> = z.object({
  id: z.string(),
  created_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  deleted_at: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ),
  creator_id: z.string(),
  evaluation_id: z.string(),
  name: z.string(),
  description: z.nullable(z.string()),
  tags: z.array(z.string()),
  metadata_: z.record(z.string(), z.any()),
  num_generations: z.int(),
  run_info: z.nullable(z.record(z.string(), z.any())).optional(),
  status: z.string().default("completed"),
  dataset_id: z.nullable(z.string()).optional(),
  evaluators: z.array(EvaluatorV2$inboundSchema),
  run_evaluators: z.array(EvaluatorV2$inboundSchema).optional(),
  system: z.nullable(SystemV2$inboundSchema).optional(),
  statistics: z.record(z.string(), EvaluatorStatistics$inboundSchema)
    .optional(),
  goal_results: z.record(z.string(), GoalResult$inboundSchema).optional(),
  passed: z.nullable(z.boolean()).optional(),
  run_scores: z.record(z.string(), EvaluationRunScoreV2$inboundSchema)
    .optional(),
  optimization: z.nullable(RunOptimizationRef$inboundSchema).optional(),
  evaluation: z.nullable(RunEvaluationSummary$inboundSchema).optional(),
  project: z.nullable(RunProjectSummary$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "deleted_at": "deletedAt",
    "creator_id": "creatorId",
    "evaluation_id": "evaluationId",
    "metadata_": "metadata",
    "num_generations": "numGenerations",
    "run_info": "runInfo",
    "dataset_id": "datasetId",
    "run_evaluators": "runEvaluators",
    "goal_results": "goalResults",
    "run_scores": "runScores",
  });
});

export function evaluationRunV2WithRefsResponseFromJSON(
  jsonString: string,
): SafeParseResult<EvaluationRunV2WithRefsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvaluationRunV2WithRefsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvaluationRunV2WithRefsResponse' from JSON`,
  );
}
