/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminatedUnion.js";
import { discriminatedUnion } from "../../types/discriminatedUnion.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ClassificationStatisticSpec,
  ClassificationStatisticSpec$inboundSchema,
} from "./classificationstatisticspec.js";
import { GoalSpec, GoalSpec$inboundSchema } from "./goalspec.js";
import {
  PercentileStatisticSpec,
  PercentileStatisticSpec$inboundSchema,
} from "./percentilestatisticspec.js";
import {
  SimpleNumericStatisticSpec,
  SimpleNumericStatisticSpec$inboundSchema,
} from "./simplenumericstatisticspec.js";

export type Statistic =
  | (SimpleNumericStatisticSpec & { kind: "avg" })
  | (SimpleNumericStatisticSpec & { kind: "count" })
  | (ClassificationStatisticSpec & { kind: "f1" })
  | (SimpleNumericStatisticSpec & { kind: "max" })
  | (SimpleNumericStatisticSpec & { kind: "min" })
  | PercentileStatisticSpec
  | (ClassificationStatisticSpec & { kind: "precision" })
  | (ClassificationStatisticSpec & { kind: "recall" })
  | (SimpleNumericStatisticSpec & { kind: "std" })
  | (SimpleNumericStatisticSpec & { kind: "sum" })
  | discriminatedUnionTypes.Unknown<"kind">;

export const EvaluatorV2Direction = {
  Maximize: "maximize",
  Minimize: "minimize",
} as const;
export type EvaluatorV2Direction = OpenEnum<typeof EvaluatorV2Direction>;

export type EvaluatorV2 = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  name: string;
  description: string | null;
  tags: Array<string>;
  numScores: number;
  goal?: GoalSpec | null | undefined;
  aggregateGoal?: GoalSpec | null | undefined;
  statistics?:
    | Array<
      | (SimpleNumericStatisticSpec & { kind: "avg" })
      | (SimpleNumericStatisticSpec & { kind: "count" })
      | (ClassificationStatisticSpec & { kind: "f1" })
      | (SimpleNumericStatisticSpec & { kind: "max" })
      | (SimpleNumericStatisticSpec & { kind: "min" })
      | PercentileStatisticSpec
      | (ClassificationStatisticSpec & { kind: "precision" })
      | (ClassificationStatisticSpec & { kind: "recall" })
      | (SimpleNumericStatisticSpec & { kind: "std" })
      | (SimpleNumericStatisticSpec & { kind: "sum" })
      | discriminatedUnionTypes.Unknown<"kind">
    >
    | null
    | undefined;
  weight: number;
  direction?: EvaluatorV2Direction | null | undefined;
  minValue?: number | null | undefined;
  maxValue?: number | null | undefined;
};

/** @internal */
export const Statistic$inboundSchema: z.ZodType<Statistic, unknown> =
  discriminatedUnion("kind", {
    avg: SimpleNumericStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("avg") }),
    ),
    count: SimpleNumericStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("count") }),
    ),
    f1: ClassificationStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("f1") }),
    ),
    max: SimpleNumericStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("max") }),
    ),
    min: SimpleNumericStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("min") }),
    ),
    percentile: PercentileStatisticSpec$inboundSchema,
    precision: ClassificationStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("precision") }),
    ),
    recall: ClassificationStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("recall") }),
    ),
    std: SimpleNumericStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("std") }),
    ),
    sum: SimpleNumericStatisticSpec$inboundSchema.and(
      z.object({ kind: z.literal("sum") }),
    ),
  });

export function statisticFromJSON(
  jsonString: string,
): SafeParseResult<Statistic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Statistic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Statistic' from JSON`,
  );
}

/** @internal */
export const EvaluatorV2Direction$inboundSchema: z.ZodType<
  EvaluatorV2Direction,
  unknown
> = openEnums.inboundSchema(EvaluatorV2Direction);

/** @internal */
export const EvaluatorV2$inboundSchema: z.ZodType<EvaluatorV2, unknown> = z
  .object({
    id: z.string(),
    created_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
    updated_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
    deleted_at: z.nullable(
      z.iso.datetime({ offset: true }).transform(v => new Date(v)),
    ),
    name: z.string(),
    description: z.nullable(z.string()),
    tags: z.array(z.string()),
    num_scores: z.int(),
    goal: z.nullable(GoalSpec$inboundSchema).optional(),
    aggregate_goal: z.nullable(GoalSpec$inboundSchema).optional(),
    statistics: z.nullable(z.array(discriminatedUnion("kind", {
      avg: SimpleNumericStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("avg") }),
      ),
      count: SimpleNumericStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("count") }),
      ),
      f1: ClassificationStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("f1") }),
      ),
      max: SimpleNumericStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("max") }),
      ),
      min: SimpleNumericStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("min") }),
      ),
      percentile: PercentileStatisticSpec$inboundSchema,
      precision: ClassificationStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("precision") }),
      ),
      recall: ClassificationStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("recall") }),
      ),
      std: SimpleNumericStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("std") }),
      ),
      sum: SimpleNumericStatisticSpec$inboundSchema.and(
        z.object({ kind: z.literal("sum") }),
      ),
    }))).optional(),
    weight: z.number().default(1),
    direction: z.nullable(EvaluatorV2Direction$inboundSchema).optional(),
    min_value: z.nullable(z.number()).optional(),
    max_value: z.nullable(z.number()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "deleted_at": "deletedAt",
      "num_scores": "numScores",
      "aggregate_goal": "aggregateGoal",
      "min_value": "minValue",
      "max_value": "maxValue",
    });
  });

export function evaluatorV2FromJSON(
  jsonString: string,
): SafeParseResult<EvaluatorV2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvaluatorV2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvaluatorV2' from JSON`,
  );
}
