/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3c73b2b3d813
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const EventProgressStatus = {
  Running: "RUNNING",
  Completed: "COMPLETED",
  Failed: "FAILED",
} as const;
export type EventProgressStatus = OpenEnum<typeof EventProgressStatus>;

/** @internal */
export const EventProgressStatus$inboundSchema: z.ZodType<
  EventProgressStatus,
  unknown
> = openEnums.inboundSchema(EventProgressStatus);
