/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a23170db3bb5
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GetSearchIndexDetailResponseSchemaModel,
  GetSearchIndexDetailResponseSchemaModel$inboundSchema,
} from "./getsearchindexdetailresponseschemamodel.js";

export type GetSearchIndexDetailResponseIndex = {
  name: string;
  vespaVersion: string | null;
  summary: string | null;
  schemas: Array<GetSearchIndexDetailResponseSchemaModel>;
};

/** @internal */
export const GetSearchIndexDetailResponseIndex$inboundSchema: z.ZodType<
  GetSearchIndexDetailResponseIndex,
  unknown
> = z.object({
  name: z.string(),
  vespa_version: z.nullable(z.string()),
  summary: z.nullable(z.string()),
  schemas: z.array(GetSearchIndexDetailResponseSchemaModel$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "vespa_version": "vespaVersion",
  });
});

export function getSearchIndexDetailResponseIndexFromJSON(
  jsonString: string,
): SafeParseResult<GetSearchIndexDetailResponseIndex, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSearchIndexDetailResponseIndex$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSearchIndexDetailResponseIndex' from JSON`,
  );
}
