/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7eb7bffdaded
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSpanFieldOptions = {
  options: Array<string> | null;
};

/** @internal */
export const GetSpanFieldOptions$inboundSchema: z.ZodType<
  GetSpanFieldOptions,
  unknown
> = z.object({
  options: z.nullable(z.array(z.string())),
});

export function getSpanFieldOptionsFromJSON(
  jsonString: string,
): SafeParseResult<GetSpanFieldOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSpanFieldOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSpanFieldOptions' from JSON`,
  );
}
