/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f2dd415a6130
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GitCommitAuthor = {
  name?: string | null | undefined;
  username?: string | null | undefined;
  htmlUrl?: string | null | undefined;
};

/** @internal */
export const GitCommitAuthor$inboundSchema: z.ZodType<
  GitCommitAuthor,
  unknown
> = z.object({
  name: z.nullable(z.string()).optional(),
  username: z.nullable(z.string()).optional(),
  html_url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "html_url": "htmlUrl",
  });
});

export function gitCommitAuthorFromJSON(
  jsonString: string,
): SafeParseResult<GitCommitAuthor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GitCommitAuthor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GitCommitAuthor' from JSON`,
  );
}
