/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 67b86956d92b
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GitCommitAuthor,
  GitCommitAuthor$inboundSchema,
} from "./gitcommitauthor.js";

export type GitCommitMetadata = {
  sha: string;
  message?: string | null | undefined;
  author?: GitCommitAuthor | null | undefined;
  htmlUrl?: string | null | undefined;
};

/** @internal */
export const GitCommitMetadata$inboundSchema: z.ZodType<
  GitCommitMetadata,
  unknown
> = z.object({
  sha: z.string(),
  message: z.nullable(z.string()).optional(),
  author: z.nullable(GitCommitAuthor$inboundSchema).optional(),
  html_url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "html_url": "htmlUrl",
  });
});

export function gitCommitMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GitCommitMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GitCommitMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GitCommitMetadata' from JSON`,
  );
}
