/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GoalSpec = {
  operator?: string | null | undefined;
  value?: any | null | undefined;
  min?: number | null | undefined;
  max?: number | null | undefined;
  values?: Array<any> | null | undefined;
  metric?: string | null | undefined;
};

/** @internal */
export const GoalSpec$inboundSchema: z.ZodType<GoalSpec, unknown> = z.object({
  operator: z.nullable(z.string()).optional(),
  value: z.nullable(z.any()).optional(),
  min: z.nullable(z.number()).optional(),
  max: z.nullable(z.number()).optional(),
  values: z.nullable(z.array(z.any())).optional(),
  metric: z.nullable(z.string()).optional(),
});

export function goalSpecFromJSON(
  jsonString: string,
): SafeParseResult<GoalSpec, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoalSpec$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoalSpec' from JSON`,
  );
}
