/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../../types/enums.js";

export const GrepMode = {
  Phrase: "phrase",
  Term: "term",
} as const;
export type GrepMode = ClosedEnum<typeof GrepMode>;

/** @internal */
export const GrepMode$outboundSchema: z.ZodEnum<typeof GrepMode> = z.enum(
  GrepMode,
);
