/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6aa92519e678
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type ImportDatasetFromExplorerRequest = {
  completionEventIds: Array<string>;
};

/** @internal */
export type ImportDatasetFromExplorerRequest$Outbound = {
  completion_event_ids: Array<string>;
};

/** @internal */
export const ImportDatasetFromExplorerRequest$outboundSchema: z.ZodType<
  ImportDatasetFromExplorerRequest$Outbound,
  ImportDatasetFromExplorerRequest
> = z.object({
  completionEventIds: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    completionEventIds: "completion_event_ids",
  });
});

export function importDatasetFromExplorerRequestToJSON(
  importDatasetFromExplorerRequest: ImportDatasetFromExplorerRequest,
): string {
  return JSON.stringify(
    ImportDatasetFromExplorerRequest$outboundSchema.parse(
      importDatasetFromExplorerRequest,
    ),
  );
}
