/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IntFieldDefinition = {
  indexed?: boolean | undefined;
  required?: boolean | undefined;
  system?: boolean | undefined;
  default?: any | null | undefined;
  type: "int";
};

/** @internal */
export const IntFieldDefinition$inboundSchema: z.ZodType<
  IntFieldDefinition,
  unknown
> = z.object({
  indexed: z.boolean().default(false),
  required: z.boolean().default(false),
  system: z.boolean().default(false),
  default: z.nullable(z.any()).optional(),
  type: z.literal("int"),
});
/** @internal */
export type IntFieldDefinition$Outbound = {
  indexed: boolean;
  required: boolean;
  system: boolean;
  default?: any | null | undefined;
  type: "int";
};

/** @internal */
export const IntFieldDefinition$outboundSchema: z.ZodType<
  IntFieldDefinition$Outbound,
  IntFieldDefinition
> = z.object({
  indexed: z.boolean().default(false),
  required: z.boolean().default(false),
  system: z.boolean().default(false),
  default: z.nullable(z.any()).optional(),
  type: z.literal("int"),
});

export function intFieldDefinitionToJSON(
  intFieldDefinition: IntFieldDefinition,
): string {
  return JSON.stringify(
    IntFieldDefinition$outboundSchema.parse(intFieldDefinition),
  );
}
export function intFieldDefinitionFromJSON(
  jsonString: string,
): SafeParseResult<IntFieldDefinition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IntFieldDefinition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IntFieldDefinition' from JSON`,
  );
}
