/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4940aefe2dff
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CreateJudgeRequest,
  CreateJudgeRequest$Outbound,
  CreateJudgeRequest$outboundSchema,
} from "./createjudgerequest.js";

export type JudgeDatasetRecordRequest = {
  judgeDefinition: CreateJudgeRequest;
};

/** @internal */
export type JudgeDatasetRecordRequest$Outbound = {
  judge_definition: CreateJudgeRequest$Outbound;
};

/** @internal */
export const JudgeDatasetRecordRequest$outboundSchema: z.ZodType<
  JudgeDatasetRecordRequest$Outbound,
  JudgeDatasetRecordRequest
> = z.object({
  judgeDefinition: CreateJudgeRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    judgeDefinition: "judge_definition",
  });
});

export function judgeDatasetRecordRequestToJSON(
  judgeDatasetRecordRequest: JudgeDatasetRecordRequest,
): string {
  return JSON.stringify(
    JudgeDatasetRecordRequest$outboundSchema.parse(judgeDatasetRecordRequest),
  );
}
