/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 659374f1ac11
 */

import * as z from "zod/v4";

export type JudgeConversationRequest = {
  messages: Array<{ [k: string]: any }>;
  properties?: { [k: string]: any } | null | undefined;
};

/** @internal */
export type JudgeConversationRequest$Outbound = {
  messages: Array<{ [k: string]: any }>;
  properties?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const JudgeConversationRequest$outboundSchema: z.ZodType<
  JudgeConversationRequest$Outbound,
  JudgeConversationRequest
> = z.object({
  messages: z.array(z.record(z.string(), z.any())),
  properties: z.nullable(z.record(z.string(), z.any())).optional(),
});

export function judgeConversationRequestToJSON(
  judgeConversationRequest: JudgeConversationRequest,
): string {
  return JSON.stringify(
    JudgeConversationRequest$outboundSchema.parse(judgeConversationRequest),
  );
}
