/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PaginatedResultOptimizationTrialWithObservations,
  PaginatedResultOptimizationTrialWithObservations$inboundSchema,
} from "./paginatedresultoptimizationtrialwithobservations.js";

export type ListOptimizationTrialsResponse = {
  trials: PaginatedResultOptimizationTrialWithObservations;
};

/** @internal */
export const ListOptimizationTrialsResponse$inboundSchema: z.ZodType<
  ListOptimizationTrialsResponse,
  unknown
> = z.object({
  trials: PaginatedResultOptimizationTrialWithObservations$inboundSchema,
});

export function listOptimizationTrialsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOptimizationTrialsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOptimizationTrialsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOptimizationTrialsResponse' from JSON`,
  );
}
