/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8f0d177737ab
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../../types/enums.js";

export const ListSortField = {
  ListSortFieldUnspecified: "list_sort_field_unspecified",
  ListSortFieldCreatedAt: "list_sort_field_created_at",
  ListSortFieldLastModifiedAt: "list_sort_field_last_modified_at",
  ListSortFieldName: "list_sort_field_name",
  ListSortFieldTitle: "list_sort_field_title",
} as const;
export type ListSortField = ClosedEnum<typeof ListSortField>;

/** @internal */
export const ListSortField$outboundSchema: z.ZodEnum<typeof ListSortField> = z
  .enum(ListSortField);
