/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LongArrayFieldDefinition = {
  indexed?: boolean | undefined;
  required?: boolean | undefined;
  system?: boolean | undefined;
  default?: any | null | undefined;
  type: "long[]";
};

/** @internal */
export const LongArrayFieldDefinition$inboundSchema: z.ZodType<
  LongArrayFieldDefinition,
  unknown
> = z.object({
  indexed: z.boolean().default(false),
  required: z.boolean().default(false),
  system: z.boolean().default(false),
  default: z.nullable(z.any()).optional(),
  type: z.literal("long[]"),
});
/** @internal */
export type LongArrayFieldDefinition$Outbound = {
  indexed: boolean;
  required: boolean;
  system: boolean;
  default?: any | null | undefined;
  type: "long[]";
};

/** @internal */
export const LongArrayFieldDefinition$outboundSchema: z.ZodType<
  LongArrayFieldDefinition$Outbound,
  LongArrayFieldDefinition
> = z.object({
  indexed: z.boolean().default(false),
  required: z.boolean().default(false),
  system: z.boolean().default(false),
  default: z.nullable(z.any()).optional(),
  type: z.literal("long[]"),
});

export function longArrayFieldDefinitionToJSON(
  longArrayFieldDefinition: LongArrayFieldDefinition,
): string {
  return JSON.stringify(
    LongArrayFieldDefinition$outboundSchema.parse(longArrayFieldDefinition),
  );
}
export function longArrayFieldDefinitionFromJSON(
  jsonString: string,
): SafeParseResult<LongArrayFieldDefinition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LongArrayFieldDefinition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LongArrayFieldDefinition' from JSON`,
  );
}
