/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5b1673c6e0b9
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ModerationDefinition = {
  model?: string | undefined;
  targetAttributes?: Array<string> | undefined;
};

/** @internal */
export const ModerationDefinition$inboundSchema: z.ZodType<
  ModerationDefinition,
  unknown
> = z.object({
  model: z.string().default("mistral-moderation-latest"),
  target_attributes: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "target_attributes": "targetAttributes",
  });
});
/** @internal */
export type ModerationDefinition$Outbound = {
  model: string;
  target_attributes?: Array<string> | undefined;
};

/** @internal */
export const ModerationDefinition$outboundSchema: z.ZodType<
  ModerationDefinition$Outbound,
  ModerationDefinition
> = z.object({
  model: z.string().default("mistral-moderation-latest"),
  targetAttributes: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    targetAttributes: "target_attributes",
  });
});

export function moderationDefinitionToJSON(
  moderationDefinition: ModerationDefinition,
): string {
  return JSON.stringify(
    ModerationDefinition$outboundSchema.parse(moderationDefinition),
  );
}
export function moderationDefinitionFromJSON(
  jsonString: string,
): SafeParseResult<ModerationDefinition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModerationDefinition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModerationDefinition' from JSON`,
  );
}
