/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 739b43737aa8
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ModerationLLMAction = {
  None: "none",
  Block: "block",
} as const;
export type ModerationLLMAction = OpenEnum<typeof ModerationLLMAction>;

/** @internal */
export const ModerationLLMAction$inboundSchema: z.ZodType<
  ModerationLLMAction,
  unknown
> = openEnums.inboundSchema(ModerationLLMAction);
/** @internal */
export const ModerationLLMAction$outboundSchema: z.ZodType<
  string,
  ModerationLLMAction
> = openEnums.outboundSchema(ModerationLLMAction);
