/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../../types/enums.js";

export const OrderByClauseDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type OrderByClauseDirection = ClosedEnum<typeof OrderByClauseDirection>;

export type OrderByClause = {
  field: string;
  direction?: OrderByClauseDirection | undefined;
};

/** @internal */
export const OrderByClauseDirection$outboundSchema: z.ZodEnum<
  typeof OrderByClauseDirection
> = z.enum(OrderByClauseDirection);

/** @internal */
export type OrderByClause$Outbound = {
  field: string;
  direction: string;
};

/** @internal */
export const OrderByClause$outboundSchema: z.ZodType<
  OrderByClause$Outbound,
  OrderByClause
> = z.object({
  field: z.string(),
  direction: OrderByClauseDirection$outboundSchema.default("asc"),
});

export function orderByClauseToJSON(orderByClause: OrderByClause): string {
  return JSON.stringify(OrderByClause$outboundSchema.parse(orderByClause));
}
