/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EvaluationRunV2Response,
  EvaluationRunV2Response$inboundSchema,
} from "./evaluationrunv2response.js";

export type PaginatedResultEvaluationRunV2Response = {
  results?: Array<EvaluationRunV2Response> | undefined;
  count: number;
  next?: string | null | undefined;
  previous?: string | null | undefined;
};

/** @internal */
export const PaginatedResultEvaluationRunV2Response$inboundSchema: z.ZodType<
  PaginatedResultEvaluationRunV2Response,
  unknown
> = z.object({
  results: z.array(EvaluationRunV2Response$inboundSchema).optional(),
  count: z.int(),
  next: z.nullable(z.string()).optional(),
  previous: z.nullable(z.string()).optional(),
});

export function paginatedResultEvaluationRunV2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResultEvaluationRunV2Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResultEvaluationRunV2Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResultEvaluationRunV2Response' from JSON`,
  );
}
