/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PipelineConfigDefinition,
  PipelineConfigDefinition$inboundSchema,
} from "./pipelineconfigdefinition.js";
import {
  PipelineConfigScope,
  PipelineConfigScope$inboundSchema,
} from "./pipelineconfigscope.js";
import {
  PipelineConfigSelector,
  PipelineConfigSelector$inboundSchema,
} from "./pipelineconfigselector.js";
import { PipelineKind, PipelineKind$inboundSchema } from "./pipelinekind.js";

export type PipelineConfig = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  scope: PipelineConfigScope;
  workspaceId: string;
  name: string;
  pipelineKind: PipelineKind;
  description?: string | null | undefined;
  selectors: Array<PipelineConfigSelector>;
  enabled: boolean;
  definition: PipelineConfigDefinition;
  definitions?: Array<PipelineConfigDefinition> | undefined;
};

/** @internal */
export const PipelineConfig$inboundSchema: z.ZodType<PipelineConfig, unknown> =
  z.object({
    id: z.string(),
    created_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
    updated_at: z.iso.datetime({ offset: true }).transform(v => new Date(v)),
    deleted_at: z.nullable(
      z.iso.datetime({ offset: true }).transform(v => new Date(v)),
    ),
    scope: PipelineConfigScope$inboundSchema,
    workspace_id: z.string(),
    name: z.string(),
    pipeline_kind: PipelineKind$inboundSchema,
    description: z.nullable(z.string()).optional(),
    selectors: z.array(PipelineConfigSelector$inboundSchema),
    enabled: z.boolean(),
    definition: PipelineConfigDefinition$inboundSchema,
    definitions: z.array(PipelineConfigDefinition$inboundSchema).optional(),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "deleted_at": "deletedAt",
      "workspace_id": "workspaceId",
      "pipeline_kind": "pipelineKind",
    });
  });

export function pipelineConfigFromJSON(
  jsonString: string,
): SafeParseResult<PipelineConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PipelineConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PipelineConfig' from JSON`,
  );
}
