/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type ReadRequest = {
  sourceId: string;
  startOffset?: number | null | undefined;
  endOffset?: number | null | undefined;
  topK?: number | undefined;
  contentType?: string | undefined;
};

/** @internal */
export type ReadRequest$Outbound = {
  source_id: string;
  start_offset?: number | null | undefined;
  end_offset?: number | null | undefined;
  top_k: number;
  content_type: string;
};

/** @internal */
export const ReadRequest$outboundSchema: z.ZodType<
  ReadRequest$Outbound,
  ReadRequest
> = z.object({
  sourceId: z.string(),
  startOffset: z.nullable(z.int()).optional(),
  endOffset: z.nullable(z.int()).optional(),
  topK: z.int().default(20),
  contentType: z.string().default("content"),
}).transform((v) => {
  return remap$(v, {
    sourceId: "source_id",
    startOffset: "start_offset",
    endOffset: "end_offset",
    topK: "top_k",
    contentType: "content_type",
  });
});

export function readRequestToJSON(readRequest: ReadRequest): string {
  return JSON.stringify(ReadRequest$outboundSchema.parse(readRequest));
}
