/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f5aa56961ad9
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ResourceType = {
  One: 1,
  Two: 2,
  Three: 3,
  Four: 4,
} as const;
export type ResourceType = OpenEnum<typeof ResourceType>;

/** @internal */
export const ResourceType$inboundSchema: z.ZodType<ResourceType, unknown> =
  openEnums.inboundSchemaInt(ResourceType);
