/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8644c3a1bbe0
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ResponseFormats = {
  Text: "text",
  JsonObject: "json_object",
  JsonSchema: "json_schema",
} as const;
export type ResponseFormats = OpenEnum<typeof ResponseFormats>;

/** @internal */
export const ResponseFormats$inboundSchema: z.ZodType<
  ResponseFormats,
  unknown
> = openEnums.inboundSchema(ResponseFormats);
/** @internal */
export const ResponseFormats$outboundSchema: z.ZodType<
  string,
  ResponseFormats
> = openEnums.outboundSchema(ResponseFormats);
