/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 14506aa40233
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const Roles = {
  System: "system",
  User: "user",
  Assistant: "assistant",
  Tool: "tool",
} as const;
export type Roles = OpenEnum<typeof Roles>;

/** @internal */
export const Roles$inboundSchema: z.ZodType<Roles, unknown> = openEnums
  .inboundSchema(Roles);
