/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 80c04a7b43d9
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const SchemaFieldDataType = {
  Int: "int",
  Bool: "bool",
  String: "string",
  Embedding: "embedding",
  Long: "long",
  Float: "float",
} as const;
export type SchemaFieldDataType = OpenEnum<typeof SchemaFieldDataType>;

/** @internal */
export const SchemaFieldDataType$inboundSchema: z.ZodType<
  SchemaFieldDataType,
  unknown
> = openEnums.inboundSchema(SchemaFieldDataType);
/** @internal */
export const SchemaFieldDataType$outboundSchema: z.ZodType<
  string,
  SchemaFieldDataType
> = openEnums.outboundSchema(SchemaFieldDataType);
