/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  NumericScoreMetric,
  NumericScoreMetric$outboundSchema,
} from "./numericscoremetric.js";
import {
  SortDirection,
  SortDirection$outboundSchema,
} from "./sortdirection.js";

export type ScoreSortInput = {
  kind: "score";
  evaluatorName: string;
  metric?: NumericScoreMetric | undefined;
  direction?: SortDirection | undefined;
};

/** @internal */
export type ScoreSortInput$Outbound = {
  kind: "score";
  evaluator_name: string;
  metric?: string | undefined;
  direction?: string | undefined;
};

/** @internal */
export const ScoreSortInput$outboundSchema: z.ZodType<
  ScoreSortInput$Outbound,
  ScoreSortInput
> = z.object({
  kind: z.literal("score"),
  evaluatorName: z.string(),
  metric: NumericScoreMetric$outboundSchema.optional(),
  direction: SortDirection$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    evaluatorName: "evaluator_name",
  });
});

export function scoreSortInputToJSON(scoreSortInput: ScoreSortInput): string {
  return JSON.stringify(ScoreSortInput$outboundSchema.parse(scoreSortInput));
}
