/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  FilterCombinator,
  FilterCombinator$outboundSchema,
} from "./filtercombinator.js";
import {
  ScoreFilter,
  ScoreFilter$Outbound,
  ScoreFilter$outboundSchema,
} from "./scorefilter.js";

export type ScoreFilterGroup = {
  combinator?: FilterCombinator | undefined;
  filters?: Array<ScoreFilter> | undefined;
};

/** @internal */
export type ScoreFilterGroup$Outbound = {
  combinator?: string | undefined;
  filters?: Array<ScoreFilter$Outbound> | undefined;
};

/** @internal */
export const ScoreFilterGroup$outboundSchema: z.ZodType<
  ScoreFilterGroup$Outbound,
  ScoreFilterGroup
> = z.object({
  combinator: FilterCombinator$outboundSchema.optional(),
  filters: z.array(ScoreFilter$outboundSchema).optional(),
});

export function scoreFilterGroupToJSON(
  scoreFilterGroup: ScoreFilterGroup,
): string {
  return JSON.stringify(
    ScoreFilterGroup$outboundSchema.parse(scoreFilterGroup),
  );
}
