/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import {
  KeywordRetriever,
  KeywordRetriever$Outbound,
  KeywordRetriever$outboundSchema,
} from "./keywordretriever.js";
import {
  NearestNeighbourRetriever,
  NearestNeighbourRetriever$Outbound,
  NearestNeighbourRetriever$outboundSchema,
} from "./nearestneighbourretriever.js";
import {
  RRFRetriever,
  RRFRetriever$Outbound,
  RRFRetriever$outboundSchema,
} from "./rrfretriever.js";

export type SearchRequestRetriever =
  | KeywordRetriever
  | NearestNeighbourRetriever
  | RRFRetriever;

export type SearchRequest = {
  retriever: KeywordRetriever | NearestNeighbourRetriever | RRFRetriever;
};

/** @internal */
export type SearchRequestRetriever$Outbound =
  | KeywordRetriever$Outbound
  | NearestNeighbourRetriever$Outbound
  | RRFRetriever$Outbound;

/** @internal */
export const SearchRequestRetriever$outboundSchema: z.ZodType<
  SearchRequestRetriever$Outbound,
  SearchRequestRetriever
> = z.union([
  KeywordRetriever$outboundSchema,
  NearestNeighbourRetriever$outboundSchema,
  RRFRetriever$outboundSchema,
]);

export function searchRequestRetrieverToJSON(
  searchRequestRetriever: SearchRequestRetriever,
): string {
  return JSON.stringify(
    SearchRequestRetriever$outboundSchema.parse(searchRequestRetriever),
  );
}

/** @internal */
export type SearchRequest$Outbound = {
  retriever:
    | KeywordRetriever$Outbound
    | NearestNeighbourRetriever$Outbound
    | RRFRetriever$Outbound;
};

/** @internal */
export const SearchRequest$outboundSchema: z.ZodType<
  SearchRequest$Outbound,
  SearchRequest
> = z.object({
  retriever: z.union([
    KeywordRetriever$outboundSchema,
    NearestNeighbourRetriever$outboundSchema,
    RRFRetriever$outboundSchema,
  ]),
});

export function searchRequestToJSON(searchRequest: SearchRequest): string {
  return JSON.stringify(SearchRequest$outboundSchema.parse(searchRequest));
}
