/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 50f5703fbb4f
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SignalWorkflowResponse = {
  message: string;
};

/** @internal */
export const SignalWorkflowResponse$inboundSchema: z.ZodType<
  SignalWorkflowResponse,
  unknown
> = z.object({
  message: z.string().default("Signal accepted"),
});

export function signalWorkflowResponseFromJSON(
  jsonString: string,
): SafeParseResult<SignalWorkflowResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SignalWorkflowResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SignalWorkflowResponse' from JSON`,
  );
}
