/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Direction to sort a service-account listing by creation time.
 */
export const SortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Direction to sort a service-account listing by creation time.
 */
export type SortOrder = ClosedEnum<typeof SortOrder>;

/** @internal */
export const SortOrder$outboundSchema: z.ZodEnum<typeof SortOrder> = z.enum(
  SortOrder,
);
