/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b07aeed7d517
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type SpanEvaluationsRequest = {
  searchExpression?: string | null | undefined;
};

/** @internal */
export type SpanEvaluationsRequest$Outbound = {
  search_expression?: string | null | undefined;
};

/** @internal */
export const SpanEvaluationsRequest$outboundSchema: z.ZodType<
  SpanEvaluationsRequest$Outbound,
  SpanEvaluationsRequest
> = z.object({
  searchExpression: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    searchExpression: "search_expression",
  });
});

export function spanEvaluationsRequestToJSON(
  spanEvaluationsRequest: SpanEvaluationsRequest,
): string {
  return JSON.stringify(
    SpanEvaluationsRequest$outboundSchema.parse(spanEvaluationsRequest),
  );
}
