/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 563b60b8536d
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../../types/enums.js";

export const SpeechOutputFormat = {
  Pcm: "pcm",
  Wav: "wav",
  Mp3: "mp3",
  Flac: "flac",
  Opus: "opus",
} as const;
export type SpeechOutputFormat = ClosedEnum<typeof SpeechOutputFormat>;

/** @internal */
export const SpeechOutputFormat$outboundSchema: z.ZodEnum<
  typeof SpeechOutputFormat
> = z.enum(SpeechOutputFormat);
