/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 199f1ffe4bef
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const SummaryStatusDollarDefs = {
  Handwritten: "handwritten",
  Generated: "generated",
  GeneratedConfirmed: "generated_confirmed",
} as const;
export type SummaryStatusDollarDefs = OpenEnum<typeof SummaryStatusDollarDefs>;

/** @internal */
export const SummaryStatusDollarDefs$inboundSchema: z.ZodType<
  SummaryStatusDollarDefs,
  unknown
> = openEnums.inboundSchema(SummaryStatusDollarDefs);
