/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e599c659fdee
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * If an error is encountered while streaming responses this is returned.
 */
export type SummaryError = {
  error: string;
};

/** @internal */
export const SummaryError$inboundSchema: z.ZodType<SummaryError, unknown> = z
  .object({
    error: z.string(),
  });

export function summaryErrorFromJSON(
  jsonString: string,
): SafeParseResult<SummaryError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SummaryError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SummaryError' from JSON`,
  );
}
