/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: daf2d5710279
 */

import * as z from "zod/v4";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const SummaryStatus = {
  Handwritten: "handwritten",
  Generated: "generated",
  GeneratedConfirmed: "generated_confirmed",
} as const;
export type SummaryStatus = OpenEnum<typeof SummaryStatus>;

/** @internal */
export const SummaryStatus$inboundSchema: z.ZodType<SummaryStatus, unknown> =
  openEnums.inboundSchema(SummaryStatus);
