/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 249109063639
 */

import * as z from "zod/v4";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Capability for tasks sampling operations.
 */
export type TasksSamplingCapability = {
  createMessage?: { [k: string]: any } | null | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const TasksSamplingCapability$inboundSchema: z.ZodType<
  TasksSamplingCapability,
  unknown
> = collectExtraKeys$(
  z.object({
    createMessage: z.nullable(z.record(z.string(), z.any())).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);

export function tasksSamplingCapabilityFromJSON(
  jsonString: string,
): SafeParseResult<TasksSamplingCapability, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TasksSamplingCapability$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TasksSamplingCapability' from JSON`,
  );
}
