/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 29e73bf9186f
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TempoTraceAttributeArrayContainer,
  TempoTraceAttributeArrayContainer$inboundSchema,
} from "./tempotraceattributearraycontainer.js";

export type TempoTraceAttributeArrayValue = {
  arrayValue: TempoTraceAttributeArrayContainer;
};

/** @internal */
export const TempoTraceAttributeArrayValue$inboundSchema: z.ZodType<
  TempoTraceAttributeArrayValue,
  unknown
> = z.object({
  arrayValue: TempoTraceAttributeArrayContainer$inboundSchema,
});

export function tempoTraceAttributeArrayValueFromJSON(
  jsonString: string,
): SafeParseResult<TempoTraceAttributeArrayValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TempoTraceAttributeArrayValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TempoTraceAttributeArrayValue' from JSON`,
  );
}
