/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1d0f1acc0101
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const ToolChoiceEnum = {
  Auto: "auto",
  None: "none",
  Any: "any",
  Required: "required",
} as const;
export type ToolChoiceEnum = ClosedEnum<typeof ToolChoiceEnum>;

/** @internal */
export const ToolChoiceEnum$outboundSchema: z.ZodNativeEnum<
  typeof ToolChoiceEnum
> = z.nativeEnum(ToolChoiceEnum);
