/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 292f8ebdbf60
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  PipelineConfigDefinition,
  PipelineConfigDefinition$Outbound,
  PipelineConfigDefinition$outboundSchema,
} from "./pipelineconfigdefinition.js";
import {
  PipelineConfigSelector,
  PipelineConfigSelector$Outbound,
  PipelineConfigSelector$outboundSchema,
} from "./pipelineconfigselector.js";
import { PipelineKind, PipelineKind$outboundSchema } from "./pipelinekind.js";

export type UpdatePipelineConfigRequest = {
  name: string;
  pipelineKind: PipelineKind;
  description?: string | null | undefined;
  selectors: Array<PipelineConfigSelector>;
  definitions: Array<PipelineConfigDefinition>;
  enabled: boolean;
};

/** @internal */
export type UpdatePipelineConfigRequest$Outbound = {
  name: string;
  pipeline_kind: string;
  description?: string | null | undefined;
  selectors: Array<PipelineConfigSelector$Outbound>;
  definitions: Array<PipelineConfigDefinition$Outbound>;
  enabled: boolean;
};

/** @internal */
export const UpdatePipelineConfigRequest$outboundSchema: z.ZodType<
  UpdatePipelineConfigRequest$Outbound,
  UpdatePipelineConfigRequest
> = z.object({
  name: z.string(),
  pipelineKind: PipelineKind$outboundSchema,
  description: z.nullable(z.string()).optional(),
  selectors: z.array(PipelineConfigSelector$outboundSchema),
  definitions: z.array(PipelineConfigDefinition$outboundSchema),
  enabled: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    pipelineKind: "pipeline_kind",
  });
});

export function updatePipelineConfigRequestToJSON(
  updatePipelineConfigRequest: UpdatePipelineConfigRequest,
): string {
  return JSON.stringify(
    UpdatePipelineConfigRequest$outboundSchema.parse(
      updatePipelineConfigRequest,
    ),
  );
}
