/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: acb3cd06c21b
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AuthenticationMethodCreateOrUpdateRequest,
  AuthenticationMethodCreateOrUpdateRequest$Outbound,
  AuthenticationMethodCreateOrUpdateRequest$outboundSchema,
} from "./authenticationmethodcreateorupdaterequest.js";

export type UpdateConnectorRequest = {
  /**
   * Optional human-readable title for the connector.
   */
  title?: string | null | undefined;
  /**
   * The name of the connector.
   */
  name?: string | null | undefined;
  /**
   * The description of the connector.
   */
  description?: string | null | undefined;
  /**
   * The optional url of the icon you want to associate to the connector.
   */
  iconUrl?: string | null | undefined;
  /**
   * Optional system prompt for the connector.
   */
  systemPrompt?: string | null | undefined;
  protocol?: "mcp" | undefined;
  /**
   * New server url for your mcp connector.
   */
  server?: string | null | undefined;
  /**
   * list of authentication methods to add to the connector or to update
   */
  authMethods?:
    | Array<AuthenticationMethodCreateOrUpdateRequest>
    | null
    | undefined;
};

/** @internal */
export type UpdateConnectorRequest$Outbound = {
  title?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  icon_url?: string | null | undefined;
  system_prompt?: string | null | undefined;
  protocol: "mcp";
  server?: string | null | undefined;
  auth_methods?:
    | Array<AuthenticationMethodCreateOrUpdateRequest$Outbound>
    | null
    | undefined;
};

/** @internal */
export const UpdateConnectorRequest$outboundSchema: z.ZodType<
  UpdateConnectorRequest$Outbound,
  UpdateConnectorRequest
> = z.object({
  title: z.nullable(z.string()).optional(),
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  iconUrl: z.nullable(z.string()).optional(),
  systemPrompt: z.nullable(z.string()).optional(),
  protocol: z.literal("mcp").default("mcp" as const),
  server: z.nullable(z.string()).optional(),
  authMethods: z.nullable(
    z.array(AuthenticationMethodCreateOrUpdateRequest$outboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    iconUrl: "icon_url",
    systemPrompt: "system_prompt",
    authMethods: "auth_methods",
  });
});

export function updateConnectorRequestToJSON(
  updateConnectorRequest: UpdateConnectorRequest,
): string {
  return JSON.stringify(
    UpdateConnectorRequest$outboundSchema.parse(updateConnectorRequest),
  );
}
