/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 222785f2237c
 */

import * as z from "zod/v4";

export type UpdateServiceAccountRequest = {
  description?: string | null | undefined;
};

/** @internal */
export type UpdateServiceAccountRequest$Outbound = {
  description?: string | null | undefined;
};

/** @internal */
export const UpdateServiceAccountRequest$outboundSchema: z.ZodType<
  UpdateServiceAccountRequest$Outbound,
  UpdateServiceAccountRequest
> = z.object({
  description: z.nullable(z.string()).optional(),
});

export function updateServiceAccountRequestToJSON(
  updateServiceAccountRequest: UpdateServiceAccountRequest,
): string {
  return JSON.stringify(
    UpdateServiceAccountRequest$outboundSchema.parse(
      updateServiceAccountRequest,
    ),
  );
}
