/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a10ea80dccd4
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  ConversationPayload,
  ConversationPayload$Outbound,
  ConversationPayload$outboundSchema,
} from "./conversationpayload.js";

export type UpdateDatasetRecordPayloadRequest = {
  conversationPayload: ConversationPayload;
};

/** @internal */
export type UpdateDatasetRecordPayloadRequest$Outbound = {
  payload: ConversationPayload$Outbound;
};

/** @internal */
export const UpdateDatasetRecordPayloadRequest$outboundSchema: z.ZodType<
  UpdateDatasetRecordPayloadRequest$Outbound,
  UpdateDatasetRecordPayloadRequest
> = z.object({
  conversationPayload: ConversationPayload$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    conversationPayload: "payload",
  });
});

export function updateDatasetRecordPayloadRequestToJSON(
  updateDatasetRecordPayloadRequest: UpdateDatasetRecordPayloadRequest,
): string {
  return JSON.stringify(
    UpdateDatasetRecordPayloadRequest$outboundSchema.parse(
      updateDatasetRecordPayloadRequest,
    ),
  );
}
