/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fef7035d7679
 */

import * as z from "zod/v4";

export type UpdateDatasetRequest = {
  name?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export type UpdateDatasetRequest$Outbound = {
  name?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const UpdateDatasetRequest$outboundSchema: z.ZodType<
  UpdateDatasetRequest$Outbound,
  UpdateDatasetRequest
> = z.object({
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
});

export function updateDatasetRequestToJSON(
  updateDatasetRequest: UpdateDatasetRequest,
): string {
  return JSON.stringify(
    UpdateDatasetRequest$outboundSchema.parse(updateDatasetRequest),
  );
}
