/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0320cfdfb195
 */

import * as z from "zod/v3";

export type UpdateLibraryRequest = {
  name?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export type UpdateLibraryRequest$Outbound = {
  name?: string | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const UpdateLibraryRequest$outboundSchema: z.ZodType<
  UpdateLibraryRequest$Outbound,
  z.ZodTypeDef,
  UpdateLibraryRequest
> = z.object({
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
});

export function updateLibraryRequestToJSON(
  updateLibraryRequest: UpdateLibraryRequest,
): string {
  return JSON.stringify(
    UpdateLibraryRequest$outboundSchema.parse(updateLibraryRequest),
  );
}
