/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 434e7fa15058
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  PipelineConfigDefinition,
  PipelineConfigDefinition$Outbound,
  PipelineConfigDefinition$outboundSchema,
} from "./pipelineconfigdefinition.js";
import {
  PipelineConfigSelector,
  PipelineConfigSelector$Outbound,
  PipelineConfigSelector$outboundSchema,
} from "./pipelineconfigselector.js";
import { PipelineKind, PipelineKind$outboundSchema } from "./pipelinekind.js";

export type UpdatePipelineConfigRequest = {
  pipelineKind: PipelineKind;
  selectors: Array<PipelineConfigSelector>;
  slug?: string | null | undefined;
  group?: string | null | undefined;
  definition: PipelineConfigDefinition;
  name: string;
  enabled: boolean;
};

/** @internal */
export type UpdatePipelineConfigRequest$Outbound = {
  pipeline_kind: string;
  selectors: Array<PipelineConfigSelector$Outbound>;
  slug?: string | null | undefined;
  group?: string | null | undefined;
  definition: PipelineConfigDefinition$Outbound;
  name: string;
  enabled: boolean;
};

/** @internal */
export const UpdatePipelineConfigRequest$outboundSchema: z.ZodType<
  UpdatePipelineConfigRequest$Outbound,
  UpdatePipelineConfigRequest
> = z.object({
  pipelineKind: PipelineKind$outboundSchema,
  selectors: z.array(PipelineConfigSelector$outboundSchema),
  slug: z.nullable(z.string()).optional(),
  group: z.nullable(z.string()).optional(),
  definition: PipelineConfigDefinition$outboundSchema,
  name: z.string(),
  enabled: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    pipelineKind: "pipeline_kind",
  });
});

export function updatePipelineConfigRequestToJSON(
  updatePipelineConfigRequest: UpdatePipelineConfigRequest,
): string {
  return JSON.stringify(
    UpdatePipelineConfigRequest$outboundSchema.parse(
      updatePipelineConfigRequest,
    ),
  );
}
