/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d87df6f4d662
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WorkflowExecutionContinuedAsNewAttributesResponse,
  WorkflowExecutionContinuedAsNewAttributesResponse$inboundSchema,
} from "./workflowexecutioncontinuedasnewattributesresponse.js";

/**
 * Emitted when a workflow continues as a new execution.
 *
 * @remarks
 *
 * This occurs when a workflow uses continue-as-new to reset its history
 * while maintaining logical continuity.
 */
export type WorkflowExecutionContinuedAsNewResponse = {
  /**
   * Unique identifier for this event instance.
   */
  eventId: string;
  /**
   * Unix timestamp in nanoseconds when the event was created.
   */
  eventTimestamp: number;
  /**
   * Execution ID of the root workflow that initiated this execution chain.
   */
  rootWorkflowExecId: string;
  /**
   * Execution ID of the parent workflow that initiated this execution. If this is a root workflow, this field is not set.
   */
  parentWorkflowExecId: string | null;
  /**
   * Execution ID of the workflow that emitted this event.
   */
  workflowExecId: string;
  /**
   * Run ID of the workflow execution. Changes on continue-as-new while workflow_exec_id stays the same.
   */
  workflowRunId: string;
  /**
   * The registered name of the workflow that emitted this event.
   */
  workflowName: string;
  /**
   * Event type discriminator.
   */
  eventType: "WORKFLOW_EXECUTION_CONTINUED_AS_NEW";
  /**
   * Attributes for workflow execution continued-as-new events.
   */
  attributes: WorkflowExecutionContinuedAsNewAttributesResponse;
};

/** @internal */
export const WorkflowExecutionContinuedAsNewResponse$inboundSchema: z.ZodType<
  WorkflowExecutionContinuedAsNewResponse,
  unknown
> = z.object({
  event_id: z.string(),
  event_timestamp: z.int(),
  root_workflow_exec_id: z.string(),
  parent_workflow_exec_id: z.nullable(z.string()),
  workflow_exec_id: z.string(),
  workflow_run_id: z.string(),
  workflow_name: z.string(),
  event_type: z.literal("WORKFLOW_EXECUTION_CONTINUED_AS_NEW").default(
    "WORKFLOW_EXECUTION_CONTINUED_AS_NEW",
  ),
  attributes: WorkflowExecutionContinuedAsNewAttributesResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "event_id": "eventId",
    "event_timestamp": "eventTimestamp",
    "root_workflow_exec_id": "rootWorkflowExecId",
    "parent_workflow_exec_id": "parentWorkflowExecId",
    "workflow_exec_id": "workflowExecId",
    "workflow_run_id": "workflowRunId",
    "workflow_name": "workflowName",
    "event_type": "eventType",
  });
});

export function workflowExecutionContinuedAsNewResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  WorkflowExecutionContinuedAsNewResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowExecutionContinuedAsNewResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WorkflowExecutionContinuedAsNewResponse' from JSON`,
  );
}
